import { countryCodeFor } from "@/lib/countries";
import type { CoachMapPoint } from "@/lib/types";

/**
 * Equirectangular projection shared with the vendored basemap
 * (src/lib/world-land-path.ts, generated by scripts/generate-world-basemap.ts).
 * Latitudes are cropped to -58..84 — Antarctica carries no coaches.
 */
export const WORLD_MAP = {
  width: 1000,
  height: 394,
  lonMin: -180,
  latMax: 84,
  scale: 1000 / 360,
} as const;

export function projectToWorldMap(lat: number, lng: number) {
  return {
    x: (lng - WORLD_MAP.lonMin) * WORLD_MAP.scale,
    y: (WORLD_MAP.latMax - lat) * WORLD_MAP.scale,
  };
}

export type CoachMapMarker = {
  x: number;
  y: number;
  r: number;
  count: number;
  /** Most common stored country string in the group — feeds the ilike filter. */
  country: string;
  /** ISO alpha-2 code when the country name resolves, for flag lookup. */
  countryCode: string | null;
  /** Distinct cities aggregated into this marker. */
  cityCount: number;
  /** Human label, e.g. "Thailand". */
  label: string;
};

export function markerRadius(count: number): number {
  return Math.min(26, Math.max(6, 4 + 2.2 * Math.sqrt(count)));
}

/**
 * Canonical grouping key for a stored country string: ISO code when the name
 * resolves, otherwise the trimmed lowercase text so unknown spellings still
 * group deterministically.
 */
export function coachCountryKey(country: string | null): string | null {
  if (!country) {
    return null;
  }
  return countryCodeFor(country) ?? country.trim().toLowerCase();
}

/**
 * Anchor overrides for countries whose coach-weighted centroid lands in open
 * water (e.g. cities split across a strait). Keyed by ISO alpha-2 code.
 */
const COUNTRY_ANCHOR_OVERRIDES: Record<string, { lat: number; lng: number }> = {};

/**
 * Aggregate city-level points into one marker per country, positioned at the
 * count-weighted centroid of that country's cities. Points without a country
 * are dropped — they cannot drive the country filter. Returned markers are
 * sorted large-first so small dots paint on top.
 */
export function buildCoachMapMarkers(points: CoachMapPoint[]): CoachMapMarker[] {
  type Group = {
    x: number;
    y: number;
    count: number;
    cities: Set<string>;
    variants: Map<string, number>;
  };
  const groups = new Map<string, Group>();

  for (const point of points) {
    const key = coachCountryKey(point.country);
    if (!key || !point.country) {
      continue;
    }

    const { x, y } = projectToWorldMap(point.lat, point.lng);
    const group = groups.get(key) ?? {
      x: 0,
      y: 0,
      count: 0,
      cities: new Set<string>(),
      variants: new Map<string, number>(),
    };

    // Weighted centroid keeps the marker anchored to the coach crowd.
    const total = group.count + point.count;
    group.x = (group.x * group.count + x * point.count) / total;
    group.y = (group.y * group.count + y * point.count) / total;
    group.count = total;
    if (point.city) {
      group.cities.add(point.city);
    }
    group.variants.set(
      point.country,
      (group.variants.get(point.country) ?? 0) + point.count,
    );
    groups.set(key, group);
  }

  const markers = [...groups.values()].map((group) => {
    const country = [...group.variants.entries()].sort((a, b) => b[1] - a[1])[0][0];
    const countryCode = countryCodeFor(country);
    const override = countryCode ? COUNTRY_ANCHOR_OVERRIDES[countryCode] : undefined;
    const anchor = override ? projectToWorldMap(override.lat, override.lng) : group;

    return {
      x: anchor.x,
      y: anchor.y,
      r: markerRadius(group.count),
      count: group.count,
      country,
      countryCode,
      cityCount: group.cities.size,
      label: country,
    };
  });

  markers.sort((a, b) => b.count - a.count);
  relaxMarkerCollisions(markers);

  return markers;
}

/**
 * Nudge overlapping country markers apart (dense regions like Southeast Asia
 * and western Europe), keeping every count label and hover target legible.
 * Displacement is capped so dots stay honest to their geography.
 */
function relaxMarkerCollisions(markers: { x: number; y: number; r: number }[]): void {
  const MAX_SHIFT = 30;
  const origin = markers.map((marker) => ({ x: marker.x, y: marker.y }));

  for (let iteration = 0; iteration < 40; iteration += 1) {
    let moved = false;
    for (let a = 0; a < markers.length; a += 1) {
      for (let b = a + 1; b < markers.length; b += 1) {
        const first = markers[a];
        const second = markers[b];
        const dx = second.x - first.x;
        const dy = second.y - first.y;
        const distance = Math.hypot(dx, dy) || 0.001;
        const minDistance = first.r + second.r + 2;
        if (distance >= minDistance) {
          continue;
        }
        const push = (minDistance - distance) / 2;
        const ux = dx / distance;
        const uy = dy / distance;
        for (const [marker, home, sign] of [
          [first, origin[a], -1],
          [second, origin[b], 1],
        ] as const) {
          const nextX = marker.x + sign * ux * push;
          const nextY = marker.y + sign * uy * push;
          if (Math.hypot(nextX - home.x, nextY - home.y) <= MAX_SHIFT) {
            marker.x = nextX;
            marker.y = nextY;
            moved = true;
          }
        }
      }
    }
    if (!moved) {
      break;
    }
  }
}
