import { countryCodeFor } from "@/lib/countries";
import { COUNTRY_CENTROIDS } from "@/lib/country-centroids";
import type { AffiliateMapEntry, CoachMapPoint } from "@/lib/types";

/**
 * Equirectangular projection shared with the vendored basemap
 * (src/lib/world-land-path.ts, generated by scripts/generate-world-basemap.ts).
 * Latitudes are cropped to -58..84 — Antarctica carries no coaches.
 */
export const WORLD_MAP = {
  width: 1000,
  height: 394,
  lonMin: -180,
  latMax: 84,
  scale: 1000 / 360,
} as const;

export function projectToWorldMap(lat: number, lng: number) {
  return {
    x: (lng - WORLD_MAP.lonMin) * WORLD_MAP.scale,
    y: (WORLD_MAP.latMax - lat) * WORLD_MAP.scale,
  };
}

export type CoachMapMarker = {
  x: number;
  y: number;
  /** Whether at least one approved coach is geocoded in the country. */
  hasCoaches: boolean;
  /** Most common stored country string in the group. */
  country: string;
  /** ISO alpha-2 code when the country name resolves, for flag lookup. */
  countryCode: string | null;
  /** Human label, e.g. "Thailand". */
  label: string;
  /** Local WIAL affiliate headquartered in this country, when one exists. */
  affiliate: { name: string } | null;
};

/**
 * Every country marker is the same size — the map shows where WIAL is present,
 * not how many coaches are listed (the full roster lives on directory.wial.org).
 */
export const MARKER_RADIUS = 7;

/**
 * Canonical grouping key for a stored country string: ISO code when the name
 * resolves, otherwise the trimmed lowercase text so unknown spellings still
 * group deterministically.
 */
export function coachCountryKey(country: string | null): string | null {
  if (!country) {
    return null;
  }
  return countryCodeFor(country) ?? country.trim().toLowerCase();
}

/**
 * Anchor overrides for countries whose coach-weighted centroid lands in open
 * water (e.g. cities split across a strait). Keyed by lowercase ISO alpha-2 code.
 */
const COUNTRY_ANCHOR_OVERRIDES: Record<string, { lat: number; lng: number }> = {};

/**
 * Directory profiles sometimes contradict themselves — a coach tagged
 * Switzerland with Montreal coordinates, Philippine coaches geocoded in North
 * Carolina. Averaging such a point into its country's anchor drags the dot into
 * open water (the Swiss marker sat mid-Atlantic). A point farther than this
 * from the country's vendored label point is treated as mis-geocoded and left
 * out of the anchor. The farthest legitimate domestic point in the roster is
 * ~2,500 km (Canada); the nearest bogus one ~6,000 km. Far corners of huge
 * countries (Vladivostok, Anchorage, Honolulu) are skipped too, which only
 * nudges that country's dot toward its main crowd.
 */
export const MAX_ANCHOR_DISTANCE_KM = 4000;

const EARTH_RADIUS_KM = 6371;

/** Great-circle distance in km between two coordinates (haversine). */
export function distanceKm(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number },
): number {
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(h));
}

/**
 * Aggregate city-level points into one marker per country, positioned at the
 * count-weighted centroid of that country's cities so the dot sits where the
 * coaches actually are. Points without a country are dropped; a point
 * implausibly far from its country (MAX_ANCHOR_DISTANCE_KM) still registers
 * presence but is left out of the anchor, and a country with no plausible
 * point anchors at its vendored label point. Affiliates
 * annotate their country's marker; an affiliate country with no mapped coaches
 * gets its own marker at the vendored country anchor (skipped when the country
 * name resolves to no ISO code). Coach markers come first, affiliate-only
 * markers after, each group in input order.
 */
export function buildCoachMapMarkers(
  points: CoachMapPoint[],
  affiliates: AffiliateMapEntry[] = [],
): CoachMapMarker[] {
  type Group = {
    x: number;
    y: number;
    /** Total count of the plausible points folded into x/y (0 = none). */
    weight: number;
    variants: Map<string, number>;
  };
  const groups = new Map<string, Group>();

  for (const point of points) {
    const key = coachCountryKey(point.country);
    if (!key || !point.country) {
      continue;
    }

    const group = groups.get(key) ?? {
      x: 0,
      y: 0,
      weight: 0,
      variants: new Map<string, number>(),
    };
    group.variants.set(
      point.country,
      (group.variants.get(point.country) ?? 0) + point.count,
    );
    groups.set(key, group);

    // A point implausibly far from its country is a directory data error: it
    // still counts as presence but must not drag the anchor into the ocean.
    const home = COUNTRY_CENTROIDS[key];
    if (home && distanceKm(point, home) > MAX_ANCHOR_DISTANCE_KM) {
      continue;
    }

    // Weighted centroid keeps the marker anchored to the coach crowd.
    const { x, y } = projectToWorldMap(point.lat, point.lng);
    const total = group.weight + point.count;
    group.x = (group.x * group.weight + x * point.count) / total;
    group.y = (group.y * group.weight + y * point.count) / total;
    group.weight = total;
  }

  const affiliateByKey = new Map<string, AffiliateMapEntry>();
  for (const affiliate of affiliates) {
    const key = coachCountryKey(affiliate.country);
    if (key && !affiliateByKey.has(key)) {
      affiliateByKey.set(key, affiliate);
    }
  }

  const markers = [...groups.entries()].map(([key, group]) => {
    const country = [...group.variants.entries()].sort((a, b) => b[1] - a[1])[0][0];
    const countryCode = countryCodeFor(country);
    const override = countryCode ? COUNTRY_ANCHOR_OVERRIDES[countryCode] : undefined;
    // No plausible point at all (every coach mis-geocoded) → vendored label point.
    const home =
      override ?? (group.weight === 0 && countryCode ? COUNTRY_CENTROIDS[countryCode] : undefined);
    const anchor = home ? projectToWorldMap(home.lat, home.lng) : group;
    const affiliate = affiliateByKey.get(key) ?? null;

    return {
      x: anchor.x,
      y: anchor.y,
      hasCoaches: true,
      country,
      countryCode,
      label: country,
      affiliate: affiliate ? { name: affiliate.name } : null,
    };
  });

  // Affiliates in countries with no mapped coaches still deserve a dot.
  for (const [key, affiliate] of affiliateByKey) {
    if (groups.has(key)) {
      continue;
    }
    const countryCode = countryCodeFor(affiliate.country);
    const home = countryCode
      ? COUNTRY_ANCHOR_OVERRIDES[countryCode] ?? COUNTRY_CENTROIDS[countryCode]
      : undefined;
    if (!countryCode || !home) {
      continue;
    }
    const anchor = projectToWorldMap(home.lat, home.lng);
    markers.push({
      x: anchor.x,
      y: anchor.y,
      hasCoaches: false,
      country: affiliate.country,
      countryCode,
      label: affiliate.country,
      affiliate: { name: affiliate.name },
    });
  }

  relaxMarkerCollisions(markers);

  return markers;
}

/**
 * Nudge overlapping country markers apart (dense regions like Southeast Asia
 * and western Europe), keeping every dot and hover target legible.
 * Displacement is capped so dots stay honest to their geography.
 */
function relaxMarkerCollisions(markers: { x: number; y: number }[]): void {
  const MAX_SHIFT = 30;
  const minDistance = 2 * MARKER_RADIUS + 2;
  const origin = markers.map((marker) => ({ x: marker.x, y: marker.y }));

  for (let iteration = 0; iteration < 40; iteration += 1) {
    let moved = false;
    for (let a = 0; a < markers.length; a += 1) {
      for (let b = a + 1; b < markers.length; b += 1) {
        const first = markers[a];
        const second = markers[b];
        const dx = second.x - first.x;
        const dy = second.y - first.y;
        const distance = Math.hypot(dx, dy) || 0.001;
        if (distance >= minDistance) {
          continue;
        }
        const push = (minDistance - distance) / 2;
        const ux = dx / distance;
        const uy = dy / distance;
        for (const [marker, home, sign] of [
          [first, origin[a], -1],
          [second, origin[b], 1],
        ] as const) {
          const nextX = marker.x + sign * ux * push;
          const nextY = marker.y + sign * uy * push;
          if (Math.hypot(nextX - home.x, nextY - home.y) <= MAX_SHIFT) {
            marker.x = nextX;
            marker.y = nextY;
            moved = true;
          }
        }
      }
    }
    if (!moved) {
      break;
    }
  }
}
