import type { CoachMapPoint } from "@/lib/types";

/**
 * Equirectangular projection shared with the vendored basemap
 * (src/lib/world-land-path.ts, generated by scripts/generate-world-basemap.ts).
 * Latitudes are cropped to -58..84 — Antarctica carries no coaches.
 */
export const WORLD_MAP = {
  width: 1000,
  height: 394,
  lonMin: -180,
  latMax: 84,
  scale: 1000 / 360,
} as const;

export function projectToWorldMap(lat: number, lng: number) {
  return {
    x: (lng - WORLD_MAP.lonMin) * WORLD_MAP.scale,
    y: (WORLD_MAP.latMax - lat) * WORLD_MAP.scale,
  };
}

export type CoachMapMarker = {
  x: number;
  y: number;
  r: number;
  count: number;
  country: string | null;
  /** Human label, e.g. "Bangkok, Thailand" or "Poland · 4 cities". */
  label: string;
};

function markerRadius(count: number): number {
  return Math.min(16, Math.max(4, 2.4 * Math.sqrt(count) + 1.6));
}

/**
 * Turn city-level points into drawable markers, merging same-country points
 * that would collide at world scale so hover targets stay unambiguous.
 * Returned markers are sorted large-first so small dots paint on top.
 */
export function buildCoachMapMarkers(points: CoachMapPoint[]): CoachMapMarker[] {
  type WorkingMarker = CoachMapMarker & { cities: Set<string> };
  const markers: WorkingMarker[] = [];
  const sorted = [...points].sort((a, b) => b.count - a.count);

  for (const point of sorted) {
    const { x, y } = projectToWorldMap(point.lat, point.lng);
    const host = markers.find((marker) => {
      if (marker.country !== point.country) {
        return false;
      }
      const distance = Math.hypot(marker.x - x, marker.y - y);
      return distance < marker.r + markerRadius(point.count) + 2;
    });

    if (host) {
      // Weighted centroid keeps the merged marker anchored to the crowd.
      const total = host.count + point.count;
      host.x = (host.x * host.count + x * point.count) / total;
      host.y = (host.y * host.count + y * point.count) / total;
      host.count = total;
      host.r = markerRadius(total);
      if (point.city) {
        host.cities.add(point.city);
      }
      continue;
    }

    markers.push({
      x,
      y,
      r: markerRadius(point.count),
      count: point.count,
      country: point.country,
      label: "",
      cities: new Set(point.city ? [point.city] : []),
    });
  }

  relaxMarkerCollisions(markers);

  return markers.map(({ cities, ...marker }) => {
    const country = marker.country ?? "Location shared on request";
    const label =
      cities.size === 1
        ? `${[...cities][0]}, ${country}`
        : cities.size > 1
          ? `${country} · ${cities.size} cities`
          : country;
    return { ...marker, label };
  });
}

/**
 * Nudge markers from different countries apart when they overlap (dense
 * regions like Southeast Asia), keeping every count label and hover target
 * legible. Displacement is capped so dots stay honest to their geography.
 */
function relaxMarkerCollisions(markers: { x: number; y: number; r: number }[]): void {
  const MAX_SHIFT = 10;
  const origin = markers.map((marker) => ({ x: marker.x, y: marker.y }));

  for (let iteration = 0; iteration < 40; iteration += 1) {
    let moved = false;
    for (let a = 0; a < markers.length; a += 1) {
      for (let b = a + 1; b < markers.length; b += 1) {
        const first = markers[a];
        const second = markers[b];
        const dx = second.x - first.x;
        const dy = second.y - first.y;
        const distance = Math.hypot(dx, dy) || 0.001;
        const minDistance = first.r + second.r + 1;
        if (distance >= minDistance) {
          continue;
        }
        const push = (minDistance - distance) / 2;
        const ux = dx / distance;
        const uy = dy / distance;
        for (const [marker, home, sign] of [
          [first, origin[a], -1],
          [second, origin[b], 1],
        ] as const) {
          const nextX = marker.x + sign * ux * push;
          const nextY = marker.y + sign * uy * push;
          if (Math.hypot(nextX - home.x, nextY - home.y) <= MAX_SHIFT) {
            marker.x = nextX;
            marker.y = nextY;
            moved = true;
          }
        }
      }
    }
    if (!moved) {
      break;
    }
  }
}
