/**
 * Generate src/lib/world-land-path.ts: an equirectangular SVG path of world
 * land masses, vendored so the coach map needs no map library or tile server.
 *
 * Source: Natural Earth 110m land (public domain), fetched from the
 * nvkelso/natural-earth-vector GitHub mirror. Run once (or when the crop
 * changes): npx tsx scripts/generate-world-basemap.ts
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson";
const OUTPUT_PATH = path.join(process.cwd(), "src", "lib", "world-land-path.ts");

// Keep in sync with WORLD_MAP in src/lib/world-map.ts.
const WIDTH = 1000;
const LON_MIN = -180;
const LAT_MAX = 84;
const LAT_MIN = -58; // crops Antarctica and empty southern ocean
const SCALE = WIDTH / 360;
const HEIGHT = Math.round((LAT_MAX - LAT_MIN) * SCALE);

type Ring = [number, number][];

function project([lon, lat]: [number, number]): [number, number] {
  return [(lon - LON_MIN) * SCALE, (LAT_MAX - lat) * SCALE];
}

function ringToPath(ring: Ring): string {
  let d = "";
  let previous: [number, number] | null = null;
  for (const point of ring) {
    const [x, y] = project(point).map((value) => Math.round(value * 10) / 10) as [number, number];
    if (!previous) {
      d += `M${x} ${y}`;
    } else if (previous[0] !== x || previous[1] !== y) {
      d += `L${x} ${y}`;
    }
    previous = [x, y];
  }
  return `${d}Z`;
}

async function main(): Promise<void> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${SOURCE_URL}: HTTP ${response.status}`);
  }
  const geojson = (await response.json()) as {
    features: { geometry: { type: string; coordinates: Ring[] | Ring[][] } }[];
  };

  const rings: Ring[] = [];
  for (const feature of geojson.features) {
    const { type, coordinates } = feature.geometry;
    const polygons = (type === "Polygon" ? [coordinates] : coordinates) as Ring[][];
    for (const polygon of polygons) {
      for (const ring of polygon) {
        const maxLat = Math.max(...ring.map((point) => point[1]));
        if (maxLat < LAT_MIN) {
          continue; // Antarctica / south of the crop
        }
        rings.push(ring);
      }
    }
  }

  const landPath = rings.map(ringToPath).join("");
  const content = `// Generated by scripts/generate-world-basemap.ts — do not edit by hand.
// Natural Earth 110m land (public domain), equirectangular projection,
// cropped to latitudes ${LAT_MIN}..${LAT_MAX}.
export const WORLD_LAND_PATH =
  "${landPath}";
`;
  await writeFile(OUTPUT_PATH, content);
  console.log(
    `Wrote ${rings.length} land rings (${(landPath.length / 1024).toFixed(1)}KB path) to ${OUTPUT_PATH}; viewBox 0 0 ${WIDTH} ${HEIGHT}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
