/**
 * Generate src/lib/country-centroids.ts: one anchor point per ISO alpha-2
 * country, vendored so the coach map can place affiliate-only markers in
 * countries that have no mapped coaches yet.
 *
 * Source: Natural Earth 50m admin_0 countries (public domain), fetched from
 * the nvkelso/natural-earth-vector GitHub mirror. The 50m set (not 110m)
 * keeps small states like Singapore. Uses each feature's LABEL_X/LABEL_Y so
 * anchors sit on land rather than at polygon centroids in open water.
 * Run once (or when the source updates): npx tsx scripts/generate-country-centroids.ts
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson";
const OUTPUT_PATH = path.join(process.cwd(), "src", "lib", "country-centroids.ts");

type FeatureProperties = Record<string, unknown>;

function isoCode(properties: FeatureProperties): string | null {
  for (const key of ["ISO_A2_EH", "ISO_A2"]) {
    const value = properties[key];
    if (typeof value === "string" && /^[A-Z]{2}$/.test(value)) {
      return value;
    }
  }
  return null;
}

async function main(): Promise<void> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${SOURCE_URL}: HTTP ${response.status}`);
  }
  const geojson = (await response.json()) as {
    features: { properties: FeatureProperties }[];
  };

  const centroids = new Map<string, { lat: number; lng: number }>();
  for (const feature of geojson.features) {
    // Lowercase to match countryCodeFor() in src/lib/countries.ts.
    const code = isoCode(feature.properties)?.toLowerCase() ?? null;
    const lat = feature.properties.LABEL_Y;
    const lng = feature.properties.LABEL_X;
    if (!code || typeof lat !== "number" || typeof lng !== "number") {
      continue;
    }
    if (!centroids.has(code)) {
      centroids.set(code, {
        lat: Math.round(lat * 100) / 100,
        lng: Math.round(lng * 100) / 100,
      });
    }
  }

  const entries = [...centroids.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, { lat, lng }]) => `  ${code}: { lat: ${lat}, lng: ${lng} },`)
    .join("\n");

  const content = `// Generated by scripts/generate-country-centroids.ts — do not edit by hand.
// Natural Earth 50m admin_0 countries (public domain) label points,
// keyed by lowercase ISO alpha-2 code (matching countryCodeFor).
export const COUNTRY_CENTROIDS: Record<string, { lat: number; lng: number }> = {
${entries}
};
`;
  await writeFile(OUTPUT_PATH, content);
  console.log(`Wrote ${centroids.size} country anchors to ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
