#!/usr/bin/env python3
"""Generate a content_pages upsert migration from a src/content/pages.json entry.

Usage:
    python3 scripts/generate-page-migration.py <slug> <outfile>

Reads the global (chapter_id = null) page with the given slug from
src/content/pages.json and writes an idempotent upsert migration, so the
fixture and the DB row cannot drift. Re-run after editing the pages.json
entry for a migration that has not shipped yet; create a new timestamped
file for pages that already shipped.
"""
import json
import sys
import textwrap


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def jsonb(value, indent):
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if isinstance(value, dict):
        parts = [f"{inner}{sql_str(k)}, {jsonb_inline(v, indent + 1)}" for k, v in value.items()]
        return "jsonb_build_object(\n" + ",\n".join(parts) + f"\n{pad})"
    if isinstance(value, list):
        parts = [f"{inner}{jsonb_inline(v, indent + 1)}" for v in value]
        return "jsonb_build_array(\n" + ",\n".join(parts) + f"\n{pad})"
    return jsonb_inline(value, indent)


def jsonb_inline(value, indent):
    if isinstance(value, (dict, list)):
        if isinstance(value, dict) and all(not isinstance(v, (dict, list)) for v in value.values()):
            parts = [f"{sql_str(k)}, {jsonb_inline(v, indent)}" for k, v in value.items()]
            one_line = "jsonb_build_object(" + ", ".join(parts) + ")"
            if len(one_line) <= 150:
                return one_line
        return jsonb(value, indent)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    return sql_str(value)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip())
    slug, outfile = sys.argv[1], sys.argv[2]

    pages = json.load(open("src/content/pages.json"))
    if isinstance(pages, dict) and "pages" in pages:
        pages = pages["pages"]
    try:
        page = next(p for p in pages if p["slug"] == slug and p["chapterId"] is None)
    except StopIteration:
        sys.exit(f"no global page with slug '{slug}' in src/content/pages.json")

    seo = page.get("seo", {})
    notes = "\n".join(
        f"--   {line}"
        for line in textwrap.wrap(seo.get("sourceNotes", ""), width=64)
    )
    header = f"""-- ============================================================
-- Migration: Upsert the "{page['title']}" page (slug: {slug})
-- Source: {seo.get('sourceUrl', 'n/a')}
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
{notes}
-- ============================================================"""

    sql = f"""{header}

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    {sql_str(page["id"])},
    null,
    {sql_str(page["slug"])},
    {sql_str(page["title"])},
    {"true" if page["published"] else "false"},
    {jsonb(page["bodyRichtext"], 1)},
    {jsonb(seo, 1)},
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
"""

    with open(outfile, "w") as f:
        f.write(sql)
    print(f"wrote {outfile} ({len(sql)} bytes)")


if __name__ == "__main__":
    main()
