-- ============================================================
-- Migration: Upsert the "Certification Information" page (slug: certification)
-- Source: https://wial.org/certification/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Consolidates wial.org/certification, /certification/foundations,
--   and /certification/calc-courses onto the bespoke /certification
--   hub (this fixture stays in sync for DB fallback and the admin
--   editor; the static route is what the public page renders). Four-
--   level pathway remains the expandable hub UI; Foundations and
--   CALC 1/2 workshop copy are native sections with anchors
--   #foundations and #calc-courses. The source Gravity Form became
--   the internal /contact CTA. Six components/two ground rules link
--   to /action-learning rather than being duplicated. Digital badges
--   stay native (Credly strip vendored under public/certification/;
--   FAQ PDF and learn-it infographic already extracted).
--   Recertification is still not rendered publicly. Legacy paths
--   /certification/foundations and /certification/calc-courses
--   redirect here.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0003',
    null,
    'certification',
    'Certification Information',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL offers four levels of certification for Action Learning coaches. Each level represents increasing expertise, experience, and leadership in the Action Learning community. WIAL is an ICF-accredited training provider, and our CALC certification is an accredited ICF CCE program.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Certification levels', 'value', '4'),
            jsonb_build_object('label', 'ICF accredited', 'value', 'CCE'),
            jsonb_build_object('label', 'Global recognition', 'value', 'Yes')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Why get certified?',
                'paragraphs', jsonb_build_array(
                    'Research shows that a trained Action Learning coach is a key success factor for Action Learning programs. More organizations now want those programs led by a Certified Action Learning Coach (CALC).',
                    'A WIAL certification also strengthens a professional''s career and their value to the organization. There are four levels, each with more education and practice behind it. WIAL is an ICF-accredited training provider, and the CALC certification is an accredited ICF CCE program.'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'Four levels of certification',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'CALC',
                        'title', 'Certified Action Learning Coach',
                        'body', 'CALCs can coach Action Learning sessions and form the first formal certification step in the WIAL model.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'PALC',
                        'title', 'Professional Action Learning Coach',
                        'body', 'PALCs have proven their ability as coaches and have accumulated meaningful WIAL Action Learning experience.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'SALC',
                        'title', 'Senior Action Learning Coach',
                        'body', 'SALCs are cleared to lead all WIAL programs and represent a higher level of experience and readiness.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'MALC',
                        'title', 'Master Action Learning Coach',
                        'body', 'MALCs are thought leaders in the Action Learning community and represent the highest level in the WIAL hierarchy.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Foundations of Action Learning',
                'paragraphs', jsonb_build_array(
                    'If you are ready for a deeper understanding of Action Learning, or are considering becoming a certified coach, this intensive two-day Foundations of Action Learning session is the next step.',
                    'The session covers the six components of Action Learning and the two ground rules in detail. Participants learn why Action Learning works, and they experience it both as a participant and as a coach.'
                ),
                'bullets', jsonb_build_array(
                    'This program is for potential coaches, organizational champions, and sponsors.',
                    'Participants earn a certificate of participation, join an Action Learning team, and observe the learning coach''s role.',
                    'WIAL can also deliver Foundations in-house; the required two days can be arranged to match an organization''s objectives.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Certification for Action Learning Coaches',
                'paragraphs', jsonb_build_array(
                    'The CALC program gives participants the skill and experience they need to coach Action Learning in demanding situations. Participants enroll in an asynchronous e-learning course, attend a live workshop, and independently lead several Action Learning sessions. Every participant coaches at least one session with a Senior or Master Action Learning Coach on the team.',
                    'Prerequisite: Foundations of Action Learning workshop. The program is for professionals who want to become certified coaches inside their organization, and for independent coaches and consultants.'
                ),
                'bullets', jsonb_build_array(
                    'CALC 1 focuses on advanced coaching methods: complete problem statements, questions aligned with the problem-solving stage, and typical group-dynamics issues.',
                    'CALC 2 focuses on organizational issues: contracting, program design, forming teams, senior-management support, and fostering a culture of Action Learning.',
                    'Certified coaches are qualified to coach Action Learning teams, manage programs, and use the WIAL brand in marketing materials.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Top skills of tomorrow',
                'paragraphs', jsonb_build_array(
                    'The CALC program develops skills identified in the World Economic Forum Future of Jobs Report 2020: analytical thinking and innovation, active learning, complex problem-solving, critical thinking, creativity, leadership and social influence, resilience, and reasoning.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Ready to get certified?',
                'body', 'Contact us to learn more about WIAL certification programs and find a certification path that is right for you.',
                'href', '/contact',
                'label', 'Contact us'
            )
        )
    ),
    jsonb_build_object(
        'description', 'WIAL certification programs — CALC, PALC, SALC, and MALC — plus Foundations of Action Learning and CALC courses for Action Learning coaches.',
        'sourceUrl', 'https://wial.org/certification/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Consolidates wial.org/certification, /certification/foundations, and /certification/calc-courses onto the bespoke /certification hub (this fixture stays in sync for DB fallback and the admin editor; the static route is what the public page renders). Four-level pathway remains the expandable hub UI; Foundations and CALC 1/2 workshop copy are native sections with anchors #foundations and #calc-courses. The source Gravity Form became the internal /contact CTA. Six components/two ground rules link to /action-learning rather than being duplicated. Digital badges stay native (Credly strip vendored under public/certification/; FAQ PDF and learn-it infographic already extracted). Recertification is still not rendered publicly. Legacy paths /certification/foundations and /certification/calc-courses redirect here.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
