-- ============================================================
-- Migration: Upsert the "WIAL Better World Fund" page (slug: better-world)
-- Source: https://wial.org/better-world-fund/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Consolidated from wial.org better-world-fund, wial-gives-back,
--   and projects (story summaries) per the crawler sheet's 'links on
--   the About page' instruction. The Nominate CTA and all eight
--   Better World story cards are now internal (#123): the
--   application form is rebuilt at /better-world/nominate
--   (better_world_applications table), and each story is its own
--   content page at better-world/<slug> with photos vendored to
--   public/better-world/stories/. The Donate CTA now opens /better-
--   world/donate (#127): the donor picks a preset or enters a custom
--   amount, and the server creates a Stripe Checkout Session with an
--   inline price for that exact amount.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0011',
    null,
    'better-world',
    'WIAL Better World Fund',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL helps to create a better world by supporting organizations that make a positive social impact. In 2015, WIAL established the Better World Fund to provide Action Learning services to community-based organizations around the world — together we can make a difference.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Fund established', 'value', '2015'),
            jsonb_build_object('label', 'Donation impact', 'value', '100x'),
            jsonb_build_object('label', 'Community projects', 'value', '10+')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Together we can make a difference',
                'paragraphs', jsonb_build_array(
                    'The Better World Fund delivers Action Learning coaching and grant support to community-based organizations around the world — nonprofits, social enterprises, and public agencies working on problems that matter.',
                    'Every dollar contributed to the Better World Fund is multiplied 100-fold through:'
                ),
                'bullets', jsonb_build_array(
                    'The powerful impact of Action Learning itself',
                    'The reduced fees and pro bono services contributed by WIAL coaches',
                    'The in-kind contributions of participating organizations'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'How your contribution helps',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', '$25',
                        'title', 'Coach learning package',
                        'body', 'Provides the learning package for training one Action Learning coach.'
                    ),
                    jsonb_build_object(
                        'eyebrow', '$50',
                        'title', 'Two coach learning packages',
                        'body', 'Provides learning packages for training two Action Learning coaches.'
                    ),
                    jsonb_build_object(
                        'eyebrow', '$100',
                        'title', 'Partial training scholarship',
                        'body', 'A partial scholarship toward four days of Action Learning training.'
                    ),
                    jsonb_build_object('eyebrow', '$250', 'title', 'Conference scholarship', 'body', 'Sends one community leader to the WIAL Global Conference.'),
                    jsonb_build_object(
                        'eyebrow', '$500',
                        'title', 'Full training scholarship',
                        'body', 'A full scholarship covering four days of Action Learning training.'
                    ),
                    jsonb_build_object('eyebrow', '$1,000', 'title', 'Team scholarship', 'body', 'A full scholarship for training an entire Action Learning team.'),
                    jsonb_build_object(
                        'eyebrow', '$2,000',
                        'title', 'Named four-day program',
                        'body', 'Funds a four-day Action Learning program designated in the donor''s name.'
                    ),
                    jsonb_build_object(
                        'eyebrow', '$5,000',
                        'title', 'Community or national program',
                        'body', 'Funds an Action Learning program serving an entire community or national organization.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'WIAL Gives Back',
                'paragraphs', jsonb_build_array(
                    'WIAL believes Action Learning is a great way to develop individuals, teams, and organizations — and to create a better world. Through WIAL Gives Back, Action Learning coaches around the world offer their coaching skills pro bono to organizations in need of help.',
                    'From May 2020 until April 2021, WIAL matched volunteer coaches with organizations, large and small, working to emerge from the COVID-19 pandemic stronger and more resilient. The projects below grew out of that initiative and the Better World Fund''s ongoing work.'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'Better World stories',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Global',
                        'title', 'International Federation of Red Cross',
                        'body', 'WIAL and IFRC leaders share the stories, successes, and future hopes of their Action Learning partnership.',
                        'href', '/better-world/ifrc-partnership',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Thailand',
                        'title', 'Hospital Administration Association',
                        'body', 'Hospital administrators used Action Learning to address complex problems in healthcare management.',
                        'href', '/better-world/thailand-hospital-administration',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Thailand',
                        'title', 'Entrepreneurship Club',
                        'body', 'Nearly 40 Thai entrepreneurs discovered Action Learning for problem-solving and leadership development.',
                        'href', '/better-world/thailand-entrepreneurship-club',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Grenada',
                        'title', 'Grenada Red Cross',
                        'body', 'Red Cross teams created breakthrough solutions to complex problems through Action Learning.',
                        'href', '/better-world/grenada-red-cross',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Malaysia',
                        'title', 'We The Protector',
                        'body', 'Be My Protector Malaysia joined WIAL Gives Back to explore Action Learning on its toughest challenges.',
                        'href', '/better-world/malaysia-we-the-protector',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Singapore',
                        'title', 'Centre for Non-Profit Leadership',
                        'body', 'Certified coaches supported nine nonprofits and more than 50 team members pro bono.',
                        'href', '/better-world/singapore-centre-for-non-profit-leadership',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Singapore',
                        'title', 'Singapore Book Council',
                        'body', 'The independent literary arts charity''s team benefited from learning WIAL''s Action Learning process.',
                        'href', '/better-world/singapore-book-council',
                        'label', 'Read the story'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Singapore',
                        'title', 'Singapore Association for the Deaf',
                        'body', 'Pro bono Action Learning coaching for the agency advocating equal opportunity for the deaf community.',
                        'href', '/better-world/singapore-association-for-the-deaf',
                        'label', 'Read the story'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Donate to the Better World Fund',
                'body', 'Every contribution is multiplied through pro bono coaching and in-kind support — and goes directly to bringing Action Learning to community organizations.',
                'href', '/better-world/donate',
                'label', 'Donate'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Nominate an organization',
                'body', 'Know a community organization that could benefit from Action Learning? Apply for Better World Fund support.',
                'href', '/better-world/nominate',
                'label', 'Nominate'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Share your Better World story',
                'body', 'Have a pro bono Action Learning story to tell? We want to hear what you have to say.',
                'href', '/contact',
                'label', 'Share your story'
            )
        )
    ),
    jsonb_build_object(
        'description', 'The WIAL Better World Fund provides Action Learning coaching and grant support to community-based organizations around the world.',
        'sourceUrl', 'https://wial.org/better-world-fund/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Consolidated from wial.org better-world-fund, wial-gives-back, and projects (story summaries) per the crawler sheet''s ''links on the About page'' instruction. The Nominate CTA and all eight Better World story cards are now internal (#123): the application form is rebuilt at /better-world/nominate (better_world_applications table), and each story is its own content page at better-world/<slug> with photos vendored to public/better-world/stories/. The Donate CTA now opens /better-world/donate (#127): the donor picks a preset or enters a custom amount, and the server creates a Stripe Checkout Session with an inline price for that exact amount.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
