-- ============================================================
-- Migration: Upsert the "WIAL Global Conferences" page (slug: conferences)
-- Source: https://wial.org/conferences/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Consolidates wial.org/conferences (empty on the source site),
--   /past-conferences (timeline entries; fixed source copy-paste
--   errors — the São Paulo description was pasted onto the Warsaw
--   2016 and Kuala Lumpur 2017 entries and Warsaw appeared twice, so
--   the factual variants were kept; the garbled 2023 title was
--   normalized to WIAL Global Action Learning Week), and /2024-wial-
--   global-conference (six text-only slide images transcribed into
--   native sections; the slides themselves are not vendored because
--   their content is fully extracted). 2026 Tokyo details verified
--   from WIAL's LinkedIn announcements and the Japan Action Learning
--   Association (jial.or.jp); registration is not yet open, so no
--   external registration link. One atmosphere photo vendored to
--   public/conferences/ (the largest variant the source exposes is
--   559px).
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0015',
    null,
    'conferences',
    'WIAL Global Conferences',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL Global Conferences bring together business leaders, HR, OD, and learning professionals, and Action Learning coaches from around the world to explore how teams solve complex problems, develop leaders, build learning organizations, and make the world a better place.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Next conference', 'value', 'Oct 23–24, 2026'),
            jsonb_build_object('label', 'Host city', 'value', 'Tokyo, Japan'),
            jsonb_build_object('label', 'Global conferences since', 'value', '2007')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Coming soon: WIAL Global Conference 2026 in Tokyo',
                'paragraphs', jsonb_build_array(
                    'The next WIAL Global Conference takes place October 23–24, 2026 at Shibuya QWS in Tokyo, Japan — marking twenty years since Action Learning arrived in Japan. Under the theme “The Rise of Future-Making Teams,” practitioners and researchers from more than a dozen countries will ask what human teams are for in an era when AI can produce answers.',
                    'The conference runs in person and online, with simultaneous Japanese–English interpretation, hosted with the Japan Action Learning Association (WIAL Japan). Registration details will be published here soon.'
                ),
                'bullets', jsonb_build_array(
                    'October 23–24, 2026 — Shibuya QWS, Tokyo, Japan',
                    'Theme: The Rise of Future-Making Teams',
                    'In person and online, with Japanese–English interpretation',
                    'Keynotes, case presentations, and live Action Learning sessions from a global speaker lineup'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'What happens at a global conference',
                'image', '/conferences/conference-discussion.jpg',
                'imageAlt', 'Participants working in a small-group discussion at a WIAL conference',
                'imagePosition', 'right',
                'paragraphs', jsonb_build_array(
                    'Each conference mixes keynotes from renowned speakers with hands-on workshops and live Action Learning sessions, so participants leave with strategies they can put to work in their own teams.',
                    'Just as importantly, it is where the global WIAL community meets: coaches, affiliates, and organizational leaders comparing real cases across countries and industries.'
                ),
                'bullets', jsonb_build_array(
                    'Learn from thought leaders in team development and leadership',
                    'Interactive sessions with strategies you can apply immediately',
                    'Network with practitioners from around the world',
                    'Success stories and case studies from real organizations'
                ),
                'caption', 'Small-group work at a WIAL conference.'
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '2024: Resilient Teams — Ho Chi Minh City, Vietnam',
                'paragraphs', jsonb_build_array(
                    'The 2024 WIAL Global Conference was held in Vietnam for the first time, on October 25–26 at the Novotel Saigon Centre in Ho Chi Minh City. Under the theme “Resilient Teams,” the two-day event equipped practitioners, corporate leaders, HR, L&D, and OD professionals, trainers, and coaches with practical strategies for building and sustaining resilient teams.',
                    'The conference was hosted with WIAL Vietnam — WIAL''s affiliate since 2015 and Affiliate of the Year 2022 — with bilingual English–Vietnamese interpretation throughout.'
                ),
                'bullets', jsonb_build_array(
                    '150 participants — practitioners, corporate leaders, HR, L&D, OD, trainers, and coaches',
                    '15+ international keynote and guest speakers',
                    'Participants from 12+ countries and 20+ industries'
                )
            ),
            jsonb_build_object(
                'type', 'timeline',
                'title', 'Past conferences',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'year', '2024',
                        'title', 'WIAL Global Conference — Ho Chi Minh City, Vietnam',
                        'body', 'October 25–26, 2024. Theme: “Resilient Teams” — the first WIAL Global Conference held in Vietnam.'
                    ),
                    jsonb_build_object(
                        'year', '2023',
                        'title', 'WIAL Global Action Learning Week',
                        'body', 'October 23–27, 2023. The annual gathering ran as a week-long global Action Learning event.'
                    ),
                    jsonb_build_object(
                        'year', '2021',
                        'title', 'WIAL Global Conference 2021',
                        'body', 'September 21–24, 2021. Business leaders, HR, OD, and learning professionals, and Action Learning coaches explored how to solve complex problems, develop leaders, build teams, and grow learning organizations.'
                    ),
                    jsonb_build_object(
                        'year', '2019',
                        'title', 'WIAL Global Conference — São Paulo, Brazil',
                        'body', 'September 26–27, 2019. The 13th annual global conference. Theme: “Building a Culture of Innovation and Collaboration through Action Learning.”'
                    ),
                    jsonb_build_object(
                        'year', '2018',
                        'title', 'WIAL Global Conference — Amsterdam, the Netherlands',
                        'body', 'September 26–27, 2018. The 12th annual global conference. Theme: “Action Learning: Fast Track Your Leaders.”'
                    ),
                    jsonb_build_object(
                        'year', '2017',
                        'title', 'WIAL Global Conference — Shanghai, China',
                        'body', 'October 19–20, 2017. The 11th annual global conference. Theme: “Transformation through Action Learning.”'
                    ),
                    jsonb_build_object(
                        'year', '2017',
                        'title', 'WIAL-USA Conference — Frederick, Maryland, USA',
                        'body', 'October 5, 2017. Theme: “Improving Performance: The Neuroscience of Action Learning.”'
                    ),
                    jsonb_build_object(
                        'year', '2017',
                        'title', 'WIAL Regional Conference — Kuala Lumpur, Malaysia',
                        'body', 'April 6–7, 2017. A regional conference for the Asia-Pacific Action Learning community.'
                    ),
                    jsonb_build_object(
                        'year', '2016',
                        'title', 'WIAL Global Conference — Warsaw, Poland',
                        'body', 'October 19–20, 2016. The 10th annual conference — nearly 100 participants came to learn, network, and experience Action Learning, with workshops on techniques and real-world implementation.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Join us at the next global conference',
                'body', 'Want to attend, speak, or bring your team to a WIAL conference? Get in touch and we''ll keep you posted as 2026 registration opens.',
                'href', '/contact',
                'label', 'Contact WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'WIAL Global Conferences: the 2026 conference in Tokyo (October 23–24, Shibuya QWS), highlights from 2024 in Ho Chi Minh City, and past conferences back to 2016.',
        'sourceUrl', 'https://wial.org/conferences/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Consolidates wial.org/conferences (empty on the source site), /past-conferences (timeline entries; fixed source copy-paste errors — the São Paulo description was pasted onto the Warsaw 2016 and Kuala Lumpur 2017 entries and Warsaw appeared twice, so the factual variants were kept; the garbled 2023 title was normalized to WIAL Global Action Learning Week), and /2024-wial-global-conference (six text-only slide images transcribed into native sections; the slides themselves are not vendored because their content is fully extracted). 2026 Tokyo details verified from WIAL''s LinkedIn announcements and the Japan Action Learning Association (jial.or.jp); registration is not yet open, so no external registration link. One atmosphere photo vendored to public/conferences/ (the largest variant the source exposes is 559px).'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
