-- ============================================================
-- Migration: Upsert the "Our Clients" page (slug: clients)
-- Source: https://wial.org/our-clients/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live wial.org Our Clients page. Client logos
--   vendored locally under public/clients/ (no hotlinking) and
--   rendered as a logo_grid matching the legacy page. Testimonials
--   from wial.org/client-testimonials/ merged in as a
--   testimonial_grid: quotes transcribed verbatim (light trims and
--   source-typo fixes; Lyreco's video and long-form case study
--   merged into one card), the two video testimonials embed via
--   youtube-nocookie, source stock photos (benefitsheader, thumbs-
--   up) and the tiny headshot skipped. Share Your Success Story
--   removed per site-owner decision (unused on the old site);
--   /client-testimonials and /share-your-success-story now redirect.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0004',
    null,
    'clients',
    'Our Clients',
    true,
    jsonb_build_object(
        'heroIntro', 'These are just some of the organizations that have worked with or continue to work with WIAL to advance the use of Action Learning in the corporate world. Want to see your business on this list? Contact us to find out how you can get involved in the Action Learning community.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Client organizations', 'value', '35+'),
            jsonb_build_object('label', 'Industries served', 'value', '10+'),
            jsonb_build_object('label', 'Years of client work', 'value', '25+')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'logo_grid',
                'title', 'Organizations we''ve worked with',
                'items', jsonb_build_array(
                    jsonb_build_object('name', 'Asian Paints', 'logo', '/clients/asian-paints.png', 'href', 'https://www.asianpaints.com/'),
                    jsonb_build_object('name', 'Boeing', 'logo', '/clients/boeing.png', 'href', 'https://www.boeing.com/'),
                    jsonb_build_object('name', 'Caterpillar', 'logo', '/clients/caterpillar.png', 'href', 'https://www.caterpillar.com/'),
                    jsonb_build_object('name', 'DuPont', 'logo', '/clients/dupont.png', 'href', 'https://www.dupont.com/'),
                    jsonb_build_object('name', 'Emerging World', 'logo', '/clients/emerging-world.png', 'href', 'https://www.emergingworld.com/'),
                    jsonb_build_object('name', 'Ernst & Young', 'logo', '/clients/ernst-young.png', 'href', 'https://www.ey.com/'),
                    jsonb_build_object('name', 'Fuji Xerox', 'logo', '/clients/fuji-xerox.png', 'href', 'https://www.fujifilm.com/fb/en'),
                    jsonb_build_object('name', 'Ministry of Education, Singapore', 'logo', '/clients/ministry-of-education.png', 'href', 'https://www.moe.gov.sg/'),
                    jsonb_build_object('name', 'NASA', 'logo', '/clients/nasa.png', 'href', 'https://www.nasa.gov/'),
                    jsonb_build_object('name', 'NEC', 'logo', '/clients/nec.png', 'href', 'https://www.nec.com/'),
                    jsonb_build_object('name', 'Microsoft', 'logo', '/clients/microsoft.png', 'href', 'https://www.microsoft.com/'),
                    jsonb_build_object('name', 'Samsung', 'logo', '/clients/samsung.png', 'href', 'https://www.samsung.com/'),
                    jsonb_build_object('name', 'Siemens', 'logo', '/clients/siemens.png', 'href', 'https://www.siemens.com/'),
                    jsonb_build_object('name', 'SIM', 'logo', '/clients/sim.png', 'href', 'https://www.sim.edu.sg/'),
                    jsonb_build_object('name', 'Toyota', 'logo', '/clients/toyota.png', 'href', 'https://global.toyota/'),
                    jsonb_build_object('name', 'Workplace Stars', 'logo', '/clients/workplace-stars.png', 'href', 'https://www.workplacestars.com/'),
                    jsonb_build_object(
                        'name', 'Grenada Red Cross',
                        'logo', '/clients/grenada-red-cross.png',
                        'href', 'https://www.ifrc.org/national-societies-directory/grenada-red-cross-society'
                    ),
                    jsonb_build_object('name', 'IFRC', 'logo', '/clients/ifrc.png', 'href', 'https://www.ifrc.org/'),
                    jsonb_build_object('name', 'Lyreco', 'logo', '/clients/lyreco.png', 'href', 'https://www.lyreco.com/'),
                    jsonb_build_object(
                        'name', 'Satellite Applications Catapult',
                        'logo', '/clients/satellite-applications-catapult.png',
                        'href', 'https://sa.catapult.org.uk/'
                    ),
                    jsonb_build_object('name', 'Pathfinders Preschool', 'logo', '/clients/pathfinders-preschool.jpg'),
                    jsonb_build_object('name', 'Takeda', 'logo', '/clients/takeda.jpg', 'href', 'https://www.takeda.com/'),
                    jsonb_build_object('name', 'HR Friday', 'logo', '/clients/hr-friday.png'),
                    jsonb_build_object('name', 'Google', 'logo', '/clients/google.png', 'href', 'https://www.google.com/'),
                    jsonb_build_object('name', 'ThoughtWorks', 'logo', '/clients/thoughtworks.png', 'href', 'https://www.thoughtworks.com/'),
                    jsonb_build_object('name', 'Aquaecology', 'logo', '/clients/aquaecology.png', 'href', 'https://www.aquaecology.group/'),
                    jsonb_build_object('name', 'Thermo Scientific', 'logo', '/clients/thermo-scientific.png', 'href', 'https://www.thermofisher.com/'),
                    jsonb_build_object('name', 'FOTIC', 'logo', '/clients/fotic.png', 'href', 'https://www.fotic.com.cn/'),
                    jsonb_build_object(
                        'name', 'Eastern Caribbean Central Bank',
                        'logo', '/clients/eastern-caribbean-central-bank.png',
                        'href', 'https://www.eccb-centralbank.org/'
                    ),
                    jsonb_build_object('name', 'Robinsons Land Corporation', 'logo', '/clients/robinsons-land.png', 'href', 'https://www.robinsonsland.com/'),
                    jsonb_build_object('name', 'Auchan Retail', 'logo', '/clients/auchan-retail.png', 'href', 'https://www.auchan-retail.com/'),
                    jsonb_build_object('name', 'MOH Holdings', 'logo', '/clients/moh-holdings.png', 'href', 'https://www.mohh.com.sg/'),
                    jsonb_build_object('name', 'AirAsia', 'logo', '/clients/airasia.png', 'href', 'https://www.airasia.com/'),
                    jsonb_build_object('name', 'US Department of Justice', 'logo', '/clients/us-department-of-justice.png', 'href', 'https://www.justice.gov/'),
                    jsonb_build_object('name', 'Basisschool Helmgras', 'logo', '/clients/helmgras.png', 'href', 'https://helmgras.tabijn.nl/'),
                    jsonb_build_object('name', 'BNP Paribas', 'logo', '/clients/bnp-paribas.jpg', 'href', 'https://group.bnpparibas/'),
                    jsonb_build_object('name', 'Thai Union Group', 'logo', '/clients/thai-union.png', 'href', 'https://www.thaiunion.com/')
                )
            ),
            jsonb_build_object(
                'type', 'testimonial_grid',
                'title', 'What clients say',
                'description', 'Organizations around the world use Action Learning to solve real problems while developing their people at the same time. Here is what their leaders say about working with WIAL.',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'organization', 'Lyreco Thailand',
                        'name', 'David Record',
                        'role', 'Managing Director',
                        'context', 'David Record talks about the power of Action Learning in transforming teams and organizations.',
                        'quote', 'I am confident that the benefits of Action Learning will continue to impact everyone who has been exposed to it, whether they remain at Lyreco or continue their career elsewhere.',
                        'logo', '/clients/lyreco.png',
                        'videoUrl', 'https://www.youtube-nocookie.com/embed/2iPGxdR9Lo8',
                        'videoTitle', 'Lyreco on the power of Action Learning'
                    ),
                    jsonb_build_object(
                        'organization', 'Satellite Applications Catapult',
                        'name', 'Kathryn Jeacock',
                        'role', 'Chief People Officer',
                        'context', 'Kathryn Jeacock talks about how Action Learning embeds key leadership skills while teams work on urgent and complex problems.',
                        'logo', '/clients/satellite-applications-catapult.png',
                        'videoUrl', 'https://www.youtube-nocookie.com/embed/XFvaYANdZWI',
                        'videoTitle', 'Satellite Applications Catapult on Action Learning'
                    ),
                    jsonb_build_object(
                        'organization', 'Google',
                        'name', 'Dr. Veronica Haight',
                        'role', 'People Operations',
                        'quote', 'WIAL Action Learning is attractive both in its structure and its results. Through the virtual session we experienced, we were able to bring Action Learning to our teams and integrate the methodology into our problem solving and decision making groups.',
                        'logo', '/clients/google.png'
                    ),
                    jsonb_build_object(
                        'organization', 'U.S. Department of Justice',
                        'name', 'Bill Thimmesh',
                        'role', 'Program Manager, Leadership and Executive Development',
                        'quote', 'Action Learning has become a key leadership development component of the Department of Justice''s ''Leadership Excellence and Achievement Program'' (LEAP) for high potentials.',
                        'logo', '/clients/us-department-of-justice.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Takeda Thailand',
                        'name', 'Peter Streibl',
                        'role', 'Country Manager',
                        'quote', 'I was genuinely impressed with the impact the Action Learning approach had on our team dynamics.',
                        'logo', '/clients/takeda.jpg'
                    ),
                    jsonb_build_object(
                        'organization', 'Thermo Fisher Scientific',
                        'name', 'David Loke',
                        'role', 'Regional Sales Training & Development Manager',
                        'quote', 'The Action Learning coaches created a safe environment for us to share about challenges and to learn. That leads to open and courageous communication among team members, and to both challenge and help others think through the issues they are facing.',
                        'logo', '/clients/thermo-scientific.png'
                    ),
                    jsonb_build_object(
                        'organization', 'ThoughtWorks China',
                        'name', 'Song Zhang',
                        'role', 'Managing Director',
                        'quote', 'The more complex the problems are, the more significant improvement in trainee''s leadership capability can be observed.',
                        'logo', '/clients/thoughtworks.png'
                    ),
                    jsonb_build_object(
                        'organization', 'AirAsia',
                        'name', 'Faz Kamaruddin',
                        'role', 'Group Head, Talent',
                        'quote', 'Our internal Certified Action Learning coaches are excited to continue and expand Action Learning as the cornerstone of the top leadership development programs for Air Asia, from Kuala Lumpur to Manila to Bangkok and more.',
                        'logo', '/clients/airasia.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Auchan Retail Ukraine',
                        'name', 'Frédéric Henin',
                        'role', 'Talent Development Director',
                        'quote', 'The WIAL Action Learning methodology is 100% in line with our goal which is to move to collaborative behaviors and helps people to be more open minded, creative and innovative.',
                        'logo', '/clients/auchan-retail.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Thai Union Group',
                        'name', 'David Giang',
                        'role', 'Head of Group Talent',
                        'quote', 'We found Action Learning effective, as it helped the leaders discover solutions through a group coaching format, simultaneously leveraging off each of their experiences as they come from different functions and regions.',
                        'logo', '/clients/thai-union.png'
                    ),
                    jsonb_build_object(
                        'organization', 'International Federation of Red Cross and Red Crescent Societies',
                        'name', 'Giorgio Ferrario',
                        'role', 'Manager, National Society Development',
                        'context', 'Many of the 192 Red Cross and Red Crescent National Societies have been facing complex organizational issues related to governance, sustainability, positioning and relationships with their national and local authorities.',
                        'quote', 'WIAL Action Learning has made a big difference in supporting them to deal with issues that are extremely difficult to solve. It also implanted seeds on a different approach to work together.',
                        'logo', '/clients/ifrc.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Grenada Red Cross',
                        'name', 'Samantha Dickson',
                        'role', 'President',
                        'quote', 'Our National Society was struggling to complete some core activities for 10 years. After engaging in the WIAL Action Learning process, we were able to literally celebrate for having resolved some of those problems in just about 2 months.',
                        'logo', '/clients/grenada-red-cross.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Eastern Caribbean Central Bank',
                        'name', 'Danny Caine',
                        'role', 'Chief of Security',
                        'quote', 'The Action Learning group segment was vital as it created accountability and heightened the importance of active listening, working collectively and giving and receiving feedback.',
                        'logo', '/clients/eastern-caribbean-central-bank.png'
                    ),
                    jsonb_build_object(
                        'organization', 'MOH Holdings, Singapore',
                        'name', 'Trevor Chua',
                        'role', 'Assistant Director',
                        'context', 'The Healthcare Leadership College under MOH Holdings used Action Learning as the foundation for its Activist for Change Programme.',
                        'quote', 'Mr Ng and the team of WIAL Action Learning Coaches were definitely a valuable resource in the development and running of the Activist for Change Programme.',
                        'logo', '/clients/moh-holdings.png'
                    ),
                    jsonb_build_object(
                        'organization', 'China Foreign Economy and Trade Trust Co., Ltd.',
                        'name', 'Teng Li',
                        'role', 'Training Manager',
                        'quote', 'Action Learning develops a systematic and deductive way of thinking and supplements participants'' intrinsic mindset and subjective experience.',
                        'logo', '/clients/fotic.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Robinsons Land Corporation',
                        'name', 'Fatima Olaguer',
                        'role', 'Associate HR Director',
                        'quote', 'The General Manager was happily surprised at the outcome of the projects and in particular the really bright ideas she didn''t expect.',
                        'logo', '/clients/robinsons-land.png'
                    ),
                    jsonb_build_object(
                        'organization', 'HR Friday',
                        'name', 'Charles Lu',
                        'role', 'Founder & CEO',
                        'quote', 'We made great progress in delivering courses and sharing sessions to Taiwan''s HR community. Four years after the start of the Action Learning program, we keep on using Action Learning in our talent development program and in our management meetings.',
                        'logo', '/clients/hr-friday.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Aquaecology',
                        'name', 'Vladimir Plasvsky',
                        'role', 'Owner',
                        'quote', 'Our meetings are now held in the manner of Action Learning, without interruptions, focusing on what was said and not on who said it.',
                        'logo', '/clients/aquaecology.png'
                    ),
                    jsonb_build_object(
                        'organization', 'Pathfinders Preschool, Mumbai',
                        'name', 'Ashwini Timblo Gupta',
                        'role', 'Owner',
                        'quote', 'I saw that when the accountability becomes ours, the collaboration just happens. We also made our environment very safe and very stimulating. I believe that Action Learning has created a new purpose for our organization to help others.',
                        'logo', '/clients/pathfinders-preschool.jpg'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Ready to bring Action Learning to your organization?',
                'body', 'Contact us to plan a tailored Action Learning program for your team or organization.',
                'href', '/contact',
                'label', 'Talk with WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Organizations that have worked with WIAL to advance Action Learning worldwide.',
        'sourceUrl', 'https://wial.org/our-clients/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live wial.org Our Clients page. Client logos vendored locally under public/clients/ (no hotlinking) and rendered as a logo_grid matching the legacy page. Testimonials from wial.org/client-testimonials/ merged in as a testimonial_grid: quotes transcribed verbatim (light trims and source-typo fixes; Lyreco''s video and long-form case study merged into one card), the two video testimonials embed via youtube-nocookie, source stock photos (benefitsheader, thumbs-up) and the tiny headshot skipped. Share Your Success Story removed per site-owner decision (unused on the old site); /client-testimonials and /share-your-success-story now redirect.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
