-- ============================================================
-- Migration: Add Our Services page and point home/action-learning
--            cards at the internal /our-services route (issue #81)
-- Generated by scripts/generate-page-migration.py from
-- src/content/pages.json — edit the fixture and regenerate
-- instead of editing this file by hand.
-- ============================================================

-- our-services
-- ============================================================
-- Migration: Upsert the "Action Learning Solutions" page (slug: our-services)
-- Source: https://wial.org/our-services/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live wial.org Our Services page (individuals,
--   teams, organizations, with session photos vendored under
--   public/our-services/). Solution Spheres framed as the four
--   outcomes WIAL documents for Action Learning (problem solving,
--   teams, leadership, culture). Homepage copy that promised five
--   service categories was aligned to this live page. Source typos
--   fixed (duplicate 'and'; EI punctuation). External contact CTA
--   replaced with internal /benefits, /coaches, and /contact routes.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0014',
    null,
    'our-services',
    'Action Learning Solutions',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL offers Action Learning solutions that help individuals, teams, and organizations solve real problems while developing people at the same time. Solution Spheres are how those results show up in your business.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Audiences', 'value', '3'),
            jsonb_build_object('label', 'Solution Spheres', 'value', '4'),
            jsonb_build_object('label', 'Delivery', 'value', 'Worldwide')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'WIAL Solution Spheres',
                'paragraphs', jsonb_build_array(
                    'WIAL''s Solution Spheres are the key to unlocking the full potential of Action Learning. Questions — not statements — are what make all four spheres possible in every session: they generate breakthrough ideas, build teams, practice leadership, and change how an organization learns.'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'Four ways Action Learning creates results',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Sphere 1',
                        'title', 'Solve urgent, complex problems',
                        'body', 'Questions open thinking that statements cannot. Teams clarify the real issue, generate options they had not considered, and leave with strategies they can act on.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Sphere 2',
                        'title', 'Build great teams',
                        'body', 'Shared inquiry builds dialogue, respect, and cohesiveness. Groups become faster at solving problems together and more committed to the results they own.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Sphere 3',
                        'title', 'Develop leadership skills',
                        'body', 'The core leadership skill in Action Learning is asking questions. Every session gives people live practice — listening, reframing, and helping others find their voice.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Sphere 4',
                        'title', 'Transform culture and capability',
                        'body', 'The learning does not stay in the room. Teams carry new habits of inquiry, decision-making, and collaboration back into the wider organization.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Action Learning helps individuals',
                'image', '/our-services/individual.jpg',
                'imageAlt', 'An Action Learning participant reflecting during a session',
                'imagePosition', 'left',
                'paragraphs', jsonb_build_array(
                    'Action Learning builds the personal skills people need to work, lead, and speak up with confidence.'
                ),
                'bullets', jsonb_build_array(
                    'Enhance personal effectiveness and productivity',
                    'Reflect on and learn from individual experience',
                    'Enhance personal leadership and soft skills',
                    'Develop self-confidence and assertiveness',
                    'Improve awareness of how assumptions, beliefs, attitudes, and organizational interests influence thinking, decisions, and actions',
                    'Develop Emotional Intelligence (EI): self-awareness, awareness of others, and adaptability',
                    'Find the courage to speak up and encourage others to do the same'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Action Learning helps teams',
                'image', '/our-services/team.jpg',
                'imageAlt', 'A team working together in an Action Learning session',
                'imagePosition', 'right',
                'paragraphs', jsonb_build_array(
                    'Action Learning turns groups of colleagues into high-performing teams that solve problems together.'
                ),
                'bullets', jsonb_build_array(
                    'Dramatically enhance team performance',
                    'Develop positive, mutually respectful working relationships with co-workers at all organizational levels',
                    'Develop individual and team problem-solving and decision-making capability',
                    'Enhance capability to reflect on and learn from collective experience',
                    'Develop awareness in the context of multicultural, diverse teams',
                    'Continually monitor and enhance team functions'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Action Learning helps organizations',
                'image', '/our-services/organization.jpg',
                'imageAlt', 'Leaders collaborating on organizational challenges through Action Learning',
                'imagePosition', 'left',
                'paragraphs', jsonb_build_array(
                    'Action Learning improves performance at every level — solving urgent challenges while building a culture of learning.'
                ),
                'bullets', jsonb_build_array(
                    'Enhance business performance at all levels',
                    'Rapidly solve urgent and important business challenges',
                    'Achieve a substantial return on investment (ROI) on organization improvement projects',
                    'Develop a culture of staff engagement, involvement, and performance',
                    'Establish effective succession planning by developing highly qualified candidates for promotion to executive leadership positions',
                    'Become a learning organization',
                    'Become more strategic in goal setting'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'See the benefits in more depth',
                'body', 'Explore how Action Learning supports problem solving, high-performing teams, leadership development, and learning organizations.',
                'href', '/benefits',
                'label', 'See the benefits'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Bring Action Learning to your organization',
                'body', 'Find a WIAL-certified coach to work with your team, or talk with us about a tailored program.',
                'href', '/coaches',
                'label', 'Find a coach'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Want more information?',
                'body', 'Contact us with questions about Action Learning solutions for your business.',
                'href', '/contact',
                'label', 'Talk with WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'WIAL Action Learning solutions for individuals, teams, and organizations — four Solution Spheres that solve problems, build teams, develop leaders, and transform culture.',
        'sourceUrl', 'https://wial.org/our-services/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live wial.org Our Services page (individuals, teams, organizations, with session photos vendored under public/our-services/). Solution Spheres framed as the four outcomes WIAL documents for Action Learning (problem solving, teams, leadership, culture). Homepage copy that promised five service categories was aligned to this live page. Source typos fixed (duplicate ''and''; EI punctuation). External contact CTA replaced with internal /benefits, /coaches, and /contact routes.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- home (What WIAL offers card now links to /our-services)
-- ============================================================
-- Migration: Upsert the "World Institute for Action Learning" page (slug: home)
-- Source: https://wial.org/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live wial.org homepage (Action Learning,
--   Solution Spheres, Benefits, People/coach directory,
--   Certification pillars, Better World Fund spotlight, newsletter
--   signup). All five What WIAL offers cards link internally
--   (/action-learning, /our-services, /benefits, /coaches,
--   /certification).
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0001',
    null,
    'home',
    'World Institute for Action Learning',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL is the world''s leading certifying body for Action Learning — a way of thinking, doing business, and working in teams that helps organizations solve real problems while developing their people at the same time.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Certification levels', 'value', '4'),
            jsonb_build_object('label', 'Solution categories', 'value', '5'),
            jsonb_build_object('label', 'Global affiliates', 'value', '8')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'What WIAL offers',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Action Learning',
                        'title', 'What is Action Learning?',
                        'body', 'A structured approach to solving urgent, real problems while building leadership and teamwork skills at the same time.',
                        'href', '/action-learning',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Solution Spheres',
                        'title', 'Action Learning solutions for your business',
                        'body', 'WIAL offers Action Learning solutions that help individuals, teams, and organizations grow.',
                        'href', '/our-services',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Benefits',
                        'title', 'Get more out of your business',
                        'body', 'See how Action Learning benefits individuals, teams, and organizations.',
                        'href', '/benefits',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'People',
                        'title', 'Search for Action Learning coaches',
                        'body', 'Find WIAL-certified coaches through the WIAL coach directory.',
                        'href', '/coaches',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Certification',
                        'title', 'The world''s leading certifying body for Action Learning',
                        'body', 'Action Learning changes the way individuals and organizations work, think, and do business.',
                        'href', '/certification',
                        'label', 'Read more'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'WIAL Better World Fund',
                'body', 'Established in 2015 to bring Action Learning services to community-based organizations around the world.',
                'href', '/better-world',
                'label', 'Learn more'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Join our newsletter',
                'body', 'Stay up to date on everything happening in Action Learning — never miss a beat.',
                'href', 'https://visitor.r20.constantcontact.com/d.jsp?llr=h87lpjrab&p=oi&m=1118083347303&sit=hbv7bh5ib&f=bd24fab6-ed5e-45b8-8360-2459192c640b',
                'label', 'Sign up'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Questions about WIAL or Action Learning?',
                'body', 'Contact us with certification questions or to learn how to get involved with a WIAL affiliate near you.',
                'href', '/contact',
                'label', 'Talk with WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Global WIAL homepage content migrated from the live wial.org homepage.',
        'sourceUrl', 'https://wial.org/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live wial.org homepage (Action Learning, Solution Spheres, Benefits, People/coach directory, Certification pillars, Better World Fund spotlight, newsletter signup). All five What WIAL offers cards link internally (/action-learning, /our-services, /benefits, /coaches, /certification).'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- action-learning (Solution Spheres CTA now links to /our-services)
-- ============================================================
-- Migration: Upsert the "What is Action Learning?" page (slug: action-learning)
-- Source: https://wial.org/action-learning/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live wial.org Action Learning page
--   (definition, six components, ground rules). External CTAs
--   replaced with internal /certification, /coaches, /our-services,
--   and /benefits routes.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0012',
    null,
    'action-learning',
    'What is Action Learning?',
    true,
    jsonb_build_object(
        'heroIntro', 'Action Learning is a process that involves a small group working on real problems, taking action, and learning as individuals, as a team, and as an organization. It solves problems and develops leaders simultaneously because its simple rules force participants to think critically and work collaboratively.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Team size', 'value', '4-8'),
            jsonb_build_object('label', 'Components', 'value', '6'),
            jsonb_build_object('label', 'Ground rules', 'value', '2')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Solving problems while developing leaders',
                'paragraphs', jsonb_build_array(
                    'Action Learning is particularly effective for solving complex problems that may appear unsolvable. It elevates the norms, the collaboration, the creativity, and the courage of groups — while each member builds their own leadership, coaching, and problem-solving skills.',
                    'The WIAL model of Action Learning took final form in the renowned six components and two ground rules below, refined through years of testing, research, and practice around the world.'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'The six components of Action Learning',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Component 1',
                        'title', 'A problem',
                        'body', 'The problem should be urgent, significant, and the responsibility of the team to resolve.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Component 2',
                        'title', 'An Action Learning group or team',
                        'body', 'The team is ideally composed of 4-8 people, ideally with diverse backgrounds and experiences.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Component 3',
                        'title', 'Insightful questioning and reflective listening',
                        'body', 'Action Learning tackles problems by first asking questions to clarify the exact nature of the problem, reflecting and identifying possible solutions, and only then taking action.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Component 4',
                        'title', 'Action taken on the problem',
                        'body', 'The group must be able to take action on the problem it is working on — members implement the strategies they develop rather than only making recommendations.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Component 5',
                        'title', 'A commitment to learning',
                        'body', 'Solving the problem brings immediate benefits, but the greater, longer-term value is the learning gained by each member and the team — and how it is applied across the organization.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Component 6',
                        'title', 'An Action Learning coach',
                        'body', 'The coach helps the team reflect on both what they are learning and how they are solving problems.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'The two ground rules',
                'paragraphs', jsonb_build_array(
                    'Two simple ground rules keep every Action Learning session focused on inquiry and learning:'
                ),
                'bullets', jsonb_build_array(
                    'Statements can only be made in response to questions — and anyone can ask questions of anyone.',
                    'The Action Learning coach has the authority to intervene whenever they see an opportunity for the team to learn.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Become a certified Action Learning coach',
                'body', 'WIAL is the world''s leading certifying body for Action Learning. Explore the certification path that fits you.',
                'href', '/certification',
                'label', 'Explore certification'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Find an Action Learning coach',
                'body', 'Search our directory of certified Action Learning coaches around the world.',
                'href', '/coaches',
                'label', 'Find a coach'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore WIAL Solution Spheres',
                'body', 'WIAL''s Solution Spheres are how Action Learning creates results for individuals, teams, and organizations.',
                'href', '/our-services',
                'label', 'See our services'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'See what Action Learning can do for you',
                'body', 'Explore how Action Learning benefits individuals, teams, and organizations.',
                'href', '/benefits',
                'label', 'See the benefits'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Action Learning is a process where a small group works on real problems, takes action, and learns as individuals, a team, and an organization — built on six components and two ground rules.',
        'sourceUrl', 'https://wial.org/action-learning/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live wial.org Action Learning page (definition, six components, ground rules). External CTAs replaced with internal /certification, /coaches, /our-services, and /benefits routes.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
