-- ============================================================
-- Migration: Partners directory + partner-logos bucket
-- Date: 2026-09-04
-- Description:
--   Organizations listed as WIAL partners, shown as a logo wall on
--   /partners (same look as the client logos on /clients) and managed by
--   platform admins at /admin/global/partners. Seeded from the official
--   directory (directory.wial.org/partners, crawled by
--   scripts/crawl-wial-partners.ts, which also vendors each logo into
--   public/partners/ and regenerates the src/content/partners.json
--   fixture). Ids are deterministic per directory slug so re-seeding
--   upserts in place; admin edits to website/description/logo win over
--   re-crawled values (coalesce below).
--   Admin-uploaded logos go to the public `partner-logos` bucket.
-- ============================================================

create table if not exists public.partners (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    name text not null,
    website_url text,
    description text,
    city text,
    state_province text,
    country text,
    country_code text,
    logo_url text,
    directory_url text,
    sort_order integer not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists partners_active_sort_idx
    on public.partners (active, sort_order, name);

alter table public.partners enable row level security;

drop policy if exists "Partners are publicly readable" on public.partners;
create policy "Partners are publicly readable"
    on public.partners
    for select
    to anon, authenticated
    using (true);

grant select on public.partners to anon, authenticated;
grant all on public.partners to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'partner-logos',
  'partner-logos',
  true,
  2097152,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Partner logos are publicly readable" on storage.objects;
create policy "Partner logos are publicly readable"
on storage.objects
for select
to public
using (bucket_id = 'partner-logos');

-- Seed: generated by `npm run crawl:partners -- --emit-sql` on 2026-09-04.
insert into public.partners
  (id, slug, name, website_url, description, city, state_province, country, country_code, logo_url, directory_url, sort_order, active)
values
  ('2930bac6-7b42-5272-aa02-a3e94fee2a81', 'appleby-associates', 'Appleby & Associates', null, null, null, null, 'United States', 'US', '/partners/appleby-associates.webp', 'https://directory.wial.org/united-states/partners/appleby-associates', 10, true),
  ('d574db8a-afd3-5ecf-9ed3-4c5d6cbd0fb1', 'asio-consulting', 'ASIO Consulting', null, 'ASIO Consulting focuses on helping teams reach excellence.
We use Action Learning to develop team cohesion and strengthen relationships between team members.', 'Klongtoey', 'Krung Thep Maha Nakhon', 'Thailand', 'TH', '/partners/asio-consulting.webp', 'https://directory.wial.org/krung-thep-maha-nakhon/klongtoey/partners/asio-consulting', 20, true),
  ('5ad33e71-361e-56f7-8b4e-ab8965c9b0b7', 'carson-consultants', 'Carson Consultants', 'http://carson-consultants.com/', 'Independent Action Learning consultants (1 employee)', 'Annapolis', 'Maryland', 'United States', 'US', '/partners/carson-consultants.webp', 'https://directory.wial.org/maryland/annapolis/partners/carson-consultants', 30, true),
  ('d2d296be-fd9c-51d3-97b5-62eb7638962d', 'corporation-for-positive-change-asia', 'Corporation for Positive Change - Asia', 'http://positivechange.asia/', null, null, 'North Carolina', 'United States', 'US', '/partners/corporation-for-positive-change-asia.webp', 'https://directory.wial.org/partners/corporation-for-positive-change-asia', 40, true),
  ('5aac47d5-e2e9-5f63-bf06-4682beecfca5', 'inquiring-dialogue-pte-ltd', 'Inquiring Dialogue Pte Ltd', null, '1 employee. Established in 2006. Offers leadership, coaching, facilitation and action learning services', 'Singapore', null, 'Singapore', 'SG', '/partners/inquiring-dialogue-pte-ltd.webp', 'https://directory.wial.org/singapore/partners/inquiring-dialogue-pte-ltd', 50, true),
  ('284f7cd7-5c90-506d-85c8-bd5e6e19ed21', 'learning-thru-action', 'Learning Thru Action', null, null, null, null, 'United States', 'US', null, 'https://directory.wial.org/united-states/partners/learning-thru-action', 60, true),
  ('c8407ba8-897b-5b18-9f4d-6d970a3ec280', 'sri-training-vietnam', 'SRI Training Vietnam', 'http://www.sri.vn/', 'Success Resources International Training Education and Investment Consulting Company Limited

Mission : “Inspiring Success”
We fulfill the development needs of thousands of people from the leading local and multinational organizations. Our signature solutions are designed and delivered in partnership with the world top organizations and experts to develop Learning and Leadership competencies. We add great value to the leaders and enable organization to achieve greater success.
VISION :
“To become the #1 innovative learning partner to corporations in Vietnam”

SRI is currently conducting in Vietnam over 50 training programs in partnership with world top organizations and experts from America, Europe, Australia and Asia.

FOUR AREAS OF SRI PROGRAMS
1. WIAL Action Learning Programs (4 programs)
2. Training For Trainers (7 programs)
3. Training For Executives (25 programs)
4. Skills Training (12 programs)', 'Ho Chi Minh City', 'Hồ Chí Minh', 'Vietnam', 'VN', '/partners/sri-training-vietnam.webp', 'https://directory.wial.org/hồ-chí-minh/ho-chi-minh-city/partners/sri-training-vietnam', 70, true),
  ('a6975c3c-02d9-5d7d-a83f-378739a76111', 'the-rizal-academy-for-innovation-and-leadership-inc', 'The Rizal Academy for Innovation and Leadership Inc.', 'http://rizalacademy.com/', null, null, 'North Carolina', 'United States', 'US', '/partners/the-rizal-academy-for-innovation-and-leadership-inc.webp', 'https://directory.wial.org/metro-manila/partners/the-rizal-academy-for-innovation-and-leadership-inc', 80, true)
on conflict (slug) do update set
  name = excluded.name,
  website_url = coalesce(public.partners.website_url, excluded.website_url),
  description = coalesce(public.partners.description, excluded.description),
  city = excluded.city,
  state_province = excluded.state_province,
  country = excluded.country,
  country_code = excluded.country_code,
  logo_url = coalesce(public.partners.logo_url, excluded.logo_url),
  directory_url = excluded.directory_url,
  updated_at = now();
