-- ============================================================
-- Migration: Upsert the "Become a WIAL Affiliate" page (slug: become-an-affiliate)
-- Source: https://wial.org/become-an-affiliate/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from wial.org/become-an-affiliate/. The
--   responsibilities list is verbatim apart from light copy edits;
--   the 'community' paragraph and the country/region guidance were
--   added so the page reads as a whole. The legacy 'Interested in
--   becoming an affiliate?' form (name, contact number, email,
--   country, message) is rebuilt with the contact-form pattern as
--   /become-an-affiliate#apply -> affiliate_inquiries (an optional
--   organization field was added). The directory.wial.org/affiliates
--   link now points to /coaches, which hosts the merged affiliate
--   directory. Two stock photos vendored to public/become-an-
--   affiliate/; the decorative Affiliates_Header banner was dropped.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0016',
    null,
    'become-an-affiliate',
    'Become a WIAL Affiliate',
    true,
    jsonb_build_object(
        'heroIntro', 'A WIAL affiliate is an organization approved by WIAL to promote WIAL Action Learning in a specific geographic region. Affiliates grow WIAL in the country where they operate, advancing Action Learning and building a community of coaches.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Foundations workshops', 'value', 'Yearly'),
            jsonb_build_object('label', 'CALC workshops', 'value', 'Every 2 years'),
            jsonb_build_object('label', 'Coach forum', 'value', 'Annual')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'What does a WIAL affiliate do?',
                'image', '/become-an-affiliate/virtual-coach-meeting.jpg',
                'imageAlt', 'A coach joining a video call with a team of Action Learning participants',
                'paragraphs', jsonb_build_array(
                    'An affiliate is WIAL''s presence in its region. It develops both aspiring and certified coaches, delivers WIAL programs locally, and keeps the regional Action Learning community connected. Affiliates:'
                ),
                'bullets', jsonb_build_array(
                    'Administer Action Learning workshops and sessions in support of developing both aspiring and certified coaches',
                    'Deliver certification and other WIAL-endorsed programs to members of their region',
                    'Mentor coaches and actively engage them to help grow their WIAL Action Learning coaching practice',
                    'Conduct Foundations workshops at least once a year and CALC workshops at least once every two years',
                    'Distribute work to coaches in their area as needed, bolstering the business of Action Learning locally',
                    'Communicate with coaches in their region about WIAL events, registration, and fees',
                    'Market and collect fees for WIAL activities, promoting Action Learning online and through their business contacts',
                    'Run an annual local or regional WIAL forum for coaches and those interested in Action Learning'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'A community, not just a license',
                'image', '/become-an-affiliate/affiliate-community-call.jpg',
                'imageAlt', 'A hybrid team meeting around a table with remote colleagues on screen',
                'imagePosition', 'right',
                'paragraphs', jsonb_build_array(
                    'Affiliates have a desire to actively develop the business of their members through mentoring and fostering a community. The strongest affiliates pair experienced coaches with newly certified ones, bring client work to their members, and give the region a regular place to practice and reflect together.',
                    'Each affiliate serves a specific country or region. Before applying, browse the directory to see whether your country already has an affiliate you could join, or whether there is an opening for a new one.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'See where WIAL is already active',
                'body', 'The coach directory shows every current affiliate on the map alongside the certified coaches based there.',
                'href', '/coaches',
                'label', 'Browse affiliates and coaches'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Learn what a WIAL affiliate does and apply to bring WIAL Action Learning to your country or region.',
        'sourceUrl', 'https://wial.org/become-an-affiliate/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from wial.org/become-an-affiliate/. The responsibilities list is verbatim apart from light copy edits; the ''community'' paragraph and the country/region guidance were added so the page reads as a whole. The legacy ''Interested in becoming an affiliate?'' form (name, contact number, email, country, message) is rebuilt with the contact-form pattern as /become-an-affiliate#apply -> affiliate_inquiries (an optional organization field was added). The directory.wial.org/affiliates link now points to /coaches, which hosts the merged affiliate directory. Two stock photos vendored to public/become-an-affiliate/; the decorative Affiliates_Header banner was dropped.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
