-- ============================================================
-- Migration: WIAL Blog posts migrated to /resources/<slug> (#121)
-- Five content pages generated from src/content/pages.json by
-- scripts/generate-page-migration.py, concatenated. Regenerate each
-- entry and re-concatenate if the fixture changes before this ships.
-- ============================================================

-- ============================================================
-- Migration: Upsert the "Culture Change? Not Without Action Learning" page (slug: resources/culture-change-not-without-action-learning)
-- Source: https://wial.org/culture-change-not-without-action-learning/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from the WIAL Blog (category/wial-blog). Text is
--   verbatim with light copy edits; the tagline 'It's about shifting
--   or changing the basic underlying assumptions' is folded into the
--   intro. The Schein passage the author quoted is rendered as a
--   native quote block. The iceberg diagram is vendored to
--   public/resources/blog/ (PNG); the wide 'CHANGE' stock
--   illustration was dropped because the square media layout cropped
--   the word. Author byline moved into an About the author section
--   and the At a glance metrics.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0018',
    null,
    'resources/culture-change-not-without-action-learning',
    'Culture Change? Not Without Action Learning',
    true,
    jsonb_build_object(
        'heroIntro', 'Culture change programs redesign offices and rewrite value statements, but rarely touch the unspoken assumptions that actually guide behavior. Peter Cauwelier, Master Action Learning Coach, on why Action Learning belongs inside every change initiative.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Published', 'value', 'Sep 2022'),
            jsonb_build_object('label', 'Author', 'value', 'Peter Cauwelier'),
            jsonb_build_object('label', 'Reading time', 'value', '4 min')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'What is culture?',
                'paragraphs', jsonb_build_array(
                    'I recently reread Edgar Schein''s seminal book Organizational Culture and Leadership. Schein identifies culture as "a pattern of shared basic assumptions learned by a group as it solved its problems of external adaptation and internal integration, which has worked well enough to be considered valid and, therefore, to be taught to new members as the correct way to perceive, think and feel in relation to those problems".'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Levels of culture',
                'image', '/resources/blog/culture-iceberg.png',
                'imageAlt', 'An iceberg with most of its mass below the waterline, the classic image for the visible and hidden levels of culture',
                'paragraphs', jsonb_build_array(
                    'Schein (and other authors) distinguish three different levels through which culture can be looked at. The first level is the artefacts, all the easily observable elements of what goes on in the organization (office layout, meeting rituals, jargon used and so on). The second is the espoused beliefs and values, and encompasses how the organization wants to show itself and be seen both internally and externally.',
                    'The basic underlying assumptions are the third level and, according to Schein, the essence of organizational culture. These assumptions are often unspoken and even unconscious. They have evolved from how the organization dealt with challenges in the past, and have stood the test of time. The basic underlying assumptions are "what works" and "the way things are around here". They are, often unconsciously, accepted by all through the shared experiences and learning from the past. They are "the implicit assumptions that actually guide behavior, that tell group members how to perceive, think about and feel about things".'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'What when we get stuck?',
                'paragraphs', jsonb_build_array(
                    'Culture is how an organization has solved its problems of external adaptation and internal integration over time. But what if the environment has changed and new ways to adapt to the external world are needed? What if there are new competitors, new business models, new customer needs, or needs that disappear? And what if the organization has grown from a single product or country to multiple products with business units around the world, requiring new ways of communicating, making decisions or building strategy? The culture for sure worked well in the past, but if the needs for external adaptation and internal integration change drastically, the ways in which the organization used to deal with these may no longer work. In other words, the organization''s culture no longer allows it to deal with these external and internal challenges and even becomes an obstacle to change.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Let''s change the culture!',
                'paragraphs', jsonb_build_array(
                    'When leadership becomes aware that the existing culture is becoming a constraint for continued growth and success, a culture change initiative is often launched. With the help of external experts, the organization will come up with new artefacts (open space to improve communication and collaboration!) and new espoused beliefs and values (a new list of values or a new tagline).',
                    'Rarely though will the underlying basic assumptions be addressed, because these are lived and felt more than expressed and managed. And although the culture change initiative gets all the fanfare and visibility that is needed, very often the old assumptions, the essence of culture according to Schein, remain the same.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Action Learning to the rescue!',
                'paragraphs', jsonb_build_array(
                    'You cannot instruct your organization to "lay bare" its basic assumptions (they are often subconscious!) and change them where needed. That just doesn''t work. And that is why change programs often scratch the surface (artefacts and espoused values) but do not fundamentally shift the basic assumptions.'
                )
            ),
            jsonb_build_object(
                'type', 'quote',
                'quote', 'Basic assumptions tend to be non-confrontable and non-debatable, and therefore extremely difficult to change. To learn something new in this realm requires us to resurrect, reexamine and possibly change some of the more stable portions of our cognitive structure, what Argyris calls double-loop learning.',
                'attribution', 'Edgar Schein, Organizational Culture and Leadership'
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Embed Action Learning in your change program',
                'paragraphs', jsonb_build_array(
                    'Action Learning is a great support to organizational change initiatives! First of all, Action Learning always deals with a real, complex, urgent and important problem. These problems are typically about external adaptation (competition, growth, market issues) or internal integration (communication, decision-making, collaboration, improving processes). Very often, when team members dive into what the "real" problem is, they will unearth, with double- and triple-loop interventions, what really underlies the symptoms that are holding back the organization. Complex and important problems are often those that exist because of the underlying culture assumptions: if the existing culture were able to deal with them, they would not be problems!',
                    'Embed Action Learning in your change program to ensure that the underlying assumptions that need to change are identified and addressed!'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'About the author',
                'paragraphs', jsonb_build_array(
                    'Peter Cauwelier is a Master Action Learning Coach (MALC) based in Thailand and the author of the WIAL-endorsed TEAM.AS.ONE Team Psychological Safety Practitioner Certification. This article was first published in September 2022.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore more Action Learning resources',
                'body', 'Case studies, books, videos, and hundreds of WIAL Talk coaching scenarios are gathered in the WIAL library.',
                'href', '/resources',
                'label', 'Back to the library'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Culture change programs rarely touch the unspoken assumptions that guide behavior. Why Action Learning belongs inside every change initiative.',
        'sourceUrl', 'https://wial.org/culture-change-not-without-action-learning/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from the WIAL Blog (category/wial-blog). Text is verbatim with light copy edits; the tagline ''It''s about shifting or changing the basic underlying assumptions'' is folded into the intro. The Schein passage the author quoted is rendered as a native quote block. The iceberg diagram is vendored to public/resources/blog/ (PNG); the wide ''CHANGE'' stock illustration was dropped because the square media layout cropped the word. Author byline moved into an About the author section and the At a glance metrics.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- ============================================================
-- Migration: Upsert the "Action Learning and Personal Leadership" page (slug: resources/action-learning-and-personal-leadership)
-- Source: https://wial.org/action-learning-personal-leadership-2/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from the WIAL Blog (category/wial-blog). Text is
--   verbatim with light copy edits (a duplicated sentence and OCR-
--   style spacing errors in the source were fixed). The source
--   featured image (a stock office photo) is vendored as the article
--   image; the second in-body stock photo was dropped as redundant.
--   Author byline moved into About the author and the At a glance
--   metrics.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0019',
    null,
    'resources/action-learning-and-personal-leadership',
    'Action Learning and Personal Leadership',
    true,
    jsonb_build_object(
        'heroIntro', 'When a team discovers it is part of its own problem, two conditions are already in place: psychological safety and the ability to reflect. Christoph Maria Ravesloot on how asking open questions develops personal leadership far beyond the session.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Published', 'value', 'Sep 2022'),
            jsonb_build_object('label', 'Author', 'value', 'Christoph Maria Ravesloot'),
            jsonb_build_object('label', 'Reading time', 'value', '3 min')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Going deep in a session',
                'image', '/resources/blog/personal-leadership-team.jpg',
                'imageAlt', 'Three colleagues looking at a laptop together',
                'paragraphs', jsonb_build_array(
                    'During an Action Learning session, the team can get to a point where one or more people discover how they are part of the problem. In a fast-changing environment around the organization and around the problem of the team, solutions are sometimes found in changing the perspective on the problem, instead of changing some parts of the chain of cause and effect in the environment of the organization.',
                    'First, it is good to know that if a team can go this far and deep into the process of Action Learning, two conditions are fulfilled:'
                ),
                'bullets', jsonb_build_array(
                    'The members of the team feel emotionally and psychologically safe.',
                    'The members of the team can personally reflect on their behavior.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Four reasons questions are hard to ask',
                'paragraphs', jsonb_build_array(
                    'This is most likely due to openness by all persons present and to good Action Learning coaching.',
                    'Second, it is good to acknowledge that through Action Learning, team members can develop their personal leadership skills. Asking open questions is not limited to Action Learning sessions. The WIAL course Leading With Questions shows how personal leadership can be developed simply by learning how to ask open questions. According to WIAL experience worldwide, there are four main reasons that make it difficult to ask questions in general:'
                ),
                'bullets', jsonb_build_array(
                    'You avoid questions out of a natural desire to protect yourself. How does that feel to you?',
                    'You are too often and too much rushed and stressed. How is that right for you?',
                    'You are not trained to ask and answer questions due to a lack of examples, training, opportunities and experience. How does this fit for you?',
                    'Your work environment discourages asking questions due to a corporate culture of adherence to existing assumptions and policies. How is or was this true for you?'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Safety first',
                'paragraphs', jsonb_build_array(
                    'The first one is the main reason for members of a team not to open up to emotion and feeling in the team. And that should be possible, since opening up is the main success factor for teams to become high performing.',
                    'So, an Action Learning coach can enable performing teams by guiding the members of a team in their personal development and leadership. The basic condition is the emotional and psychological safety in the team, during the sessions and outside the sessions. It is up to the Action Learning coach to personally intervene in the sessions whenever the team can learn how to secure safety only by asking open questions.',
                    'So, any team, guided and coached to discover the benefits of asking questions the Action Learning way, will sooner or later be able to feel safe and to perform higher. Higher performance gives access to coping with fast-changing environments and highly complex problems.',
                    'What personal development do you as a leader prefer, to coach teams safely?'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'About the author',
                'paragraphs', jsonb_build_array(
                    'Prof. dr. Christoph Maria Ravesloot is a Professional Action Learning Coach (PALC), Director of Action Research at WIAL Netherlands, and CEO of Action Learning WIAL Germany. This article was first published in September 2022.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore more Action Learning resources',
                'body', 'Case studies, books, videos, and hundreds of WIAL Talk coaching scenarios are gathered in the WIAL library.',
                'href', '/resources',
                'label', 'Back to the library'
            )
        )
    ),
    jsonb_build_object(
        'description', 'How Action Learning develops personal leadership: psychological safety, reflection, and the four reasons people find it hard to ask open questions.',
        'sourceUrl', 'https://wial.org/action-learning-personal-leadership-2/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from the WIAL Blog (category/wial-blog). Text is verbatim with light copy edits (a duplicated sentence and OCR-style spacing errors in the source were fixed). The source featured image (a stock office photo) is vendored as the article image; the second in-body stock photo was dropped as redundant. Author byline moved into About the author and the At a glance metrics.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- ============================================================
-- Migration: Upsert the "A Fresh Look at Ground Rule #1" page (slug: resources/action-learning-ground-rule-1)
-- Source: https://wial.org/fresh-look-ground-rule-1-call-apply-strictly-coach/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from the WIAL Blog (category/wial-blog); the source
--   title's subtitle ('And a call to apply it strictly as a coach!')
--   is covered by the intro. Text is verbatim with light copy edits
--   and source typos fixed ('uestion'). Both source images vendored
--   to public/resources/blog/ (featured stock photo and the
--   question-mark illustration the author placed mid-article). Slug
--   shortened to action-learning-ground-rule-1 for search; the
--   legacy URL redirects here.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0020',
    null,
    'resources/action-learning-ground-rule-1',
    'A Fresh Look at Ground Rule #1',
    true,
    jsonb_build_object(
        'heroIntro', 'Statements can only be made in response to questions. Peter Cauwelier argues there is no such thing as a long question, and that a WIAL coach should intervene after fifteen seconds to keep the rule alive in spirit, not just in grammar.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Published', 'value', 'Jun 2022'),
            jsonb_build_object('label', 'Author', 'value', 'Peter Cauwelier'),
            jsonb_build_object('label', 'Reading time', 'value', '5 min')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'Ground Rule #1',
                'image', '/resources/blog/ground-rule-1-coaching-session.jpg',
                'imageAlt', 'A team working with laptops and sticky notes on a whiteboard',
                'paragraphs', jsonb_build_array(
                    'If there''s anything a WIAL Action Learning coach remembers from their certification program, it is the power of WIAL''s Ground Rule #1: statements can only be made in response to questions (and anyone can ask a question of anyone else). This ground rule is what makes WIAL Action Learning so powerful, and so different from other forms of Action Learning.',
                    'A coach starts each session with a reminder of both ground rules, to ensure the team members are aligned with the rules necessary for a successful Action Learning session. And then, off we go!'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Who has the next question?',
                'paragraphs', jsonb_build_array(
                    'For sure the session starts off with a few questions (and sometimes a bit of hesitation) followed by some answers. All is good: Ground Rule #1 in full swing! Yet very often, and very quickly, questions tend to get longer. Some questions are preceded by an "introduction" or explanation about the question that is about to follow.',
                    '"John, it seems that there is a bit of something going on and also maybe something else, so my question is, how do you feel about this?" Or a question is followed by some sort of elaboration, as if the question needs to be put in perspective, clarified or expanded upon. When "because" slips into a question, the person asking is in fact about to answer their own question. "So Susan, how do you feel about this situation, because it seems from what you said earlier that something, but maybe it could also be that there is something else?"',
                    'At some point, I used to intervene about "long questions". "Team, are we asking more short questions or more long questions? What is the impact if we ask this or that kind of question?" It took me a while to realize that there are no long questions.'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'There are no long questions',
                'image', '/resources/blog/ground-rule-1-questions.jpg',
                'imageAlt', 'A glowing question mark among many dimmer question marks',
                'imagePosition', 'right',
                'paragraphs', jsonb_build_array(
                    'There is no such thing as a long question. When a question gets long, it stops being a question. It may start off with a question word, but then the question gets killed off in a series of twists and turns and additions and explanations. By the time the long-winded so-called question comes to an end, the team member to whom it is addressed will likely ask "Er, what was the question again?"',
                    'Unfortunately, many coaches (I have been guilty, but am getting better) are way too flexible with Ground Rule #1. The ground rule states that statements can only be made in response to questions. It does not state that one can elaborate, add, explain, clarify and expand without end, as long as there is a question somewhere in there, either at the start or at the end of the rambling. Quite often the coach will be listening closely and, as long as a question word (who, what, how) is uttered, will consider that there was a question there.',
                    'There are many advantages to asking questions in Action Learning. One of the main reasons we ask questions is to develop genuine curiosity: putting oneself in others'' shoes, and exploring their problem and its context without judgment. Questions that are followed by long elaborations, explanations and clarifications are not genuine or curious questions. The same goes for questions that come at the end of a long-winded description. They may grammatically start off or get wrapped up as a question, but they are not questions in the spirit of WIAL Action Learning, and a WIAL coach should not allow them.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Intervene (aka interrupt)!',
                'paragraphs', jsonb_build_array(
                    'As a coach, you know after 15 seconds if someone is asking a question or not. Yes, you read that well: 15 seconds. In spoken language, 15 seconds corresponds to around 30 words. Try and ask a genuine question that is 30 words long: you will not succeed. There is no such thing as a long question. If you count the questions in Choon Seng Ng''s book What''s Your Question and add them to the number of questions in Power Questions by Andrew Sobel and Jerold Panas, you come to a total of 967 questions. I could not find any question amongst the 967 that has more than 20 words.',
                    'As a coach, if a "question" goes on beyond 15 seconds or 30 words, you can be pretty certain that Ground Rule #1 is being broken. So intervene! Yes, after 15 seconds.',
                    'A coach should not be aggressive, but at the same time, why wait for the so-called "question" to end (after 30? 45? 60 seconds or more?) if you know after 15 seconds that Ground Rule #1 is being broken. If you do not intervene, the team members get into the habit of explaining, talking, clarifying or elaborating with a question somewhere thrown in at the end. They think they are asking questions.',
                    'So after 15 seconds, with the "question" still going on, I lean in, smile and ask "And so your question is?" Sometimes I get a reaction like "Yes, but I am explaining why I am asking my question!" to which I answer, with a smile, "That''s OK, just ask your question!" After a few times, team members learn (!) and see the power of asking real, curious questions, without explanations before or after. And then we can have a real Action Learning session!'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Honor Ground Rule #1',
                'paragraphs', jsonb_build_array(
                    'Ground Rule #1 is what makes WIAL Action Learning powerful. As coaches, we need to ensure that the ground rule is really followed, not just "mechanically" or grammatically, but also in the spirit of asking curious questions. Interrupt so-called long questions after 15 seconds: the team will gain tremendously from it!'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'About the author',
                'paragraphs', jsonb_build_array(
                    'Peter Cauwelier is a Master Action Learning Coach (MALC) based in Thailand. This article was first published in June 2022.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore more Action Learning resources',
                'body', 'Case studies, books, videos, and hundreds of WIAL Talk coaching scenarios are gathered in the WIAL library.',
                'href', '/resources',
                'label', 'Back to the library'
            )
        )
    ),
    jsonb_build_object(
        'description', 'There is no such thing as a long question. Why a WIAL Action Learning coach should intervene after 15 seconds to honor Ground Rule #1.',
        'sourceUrl', 'https://wial.org/fresh-look-ground-rule-1-call-apply-strictly-coach/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from the WIAL Blog (category/wial-blog); the source title''s subtitle (''And a call to apply it strictly as a coach!'') is covered by the intro. Text is verbatim with light copy edits and source typos fixed (''uestion''). Both source images vendored to public/resources/blog/ (featured stock photo and the question-mark illustration the author placed mid-article). Slug shortened to action-learning-ground-rule-1 for search; the legacy URL redirects here.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- ============================================================
-- Migration: Upsert the "Rikkyo University Receives the WIAL Global Award in the Academic Sector" page (slug: resources/rikkyo-university-wial-global-award)
-- Source: https://wial.org/rikkyo-university-receives-wial-global-award-academic-sector/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from the sibling 'blog' category (category/blog), which
--   is not linked from the wial.org menu. Text is verbatim with
--   light copy edits; the bracketed source headings '[Comment by
--   Prof. Higano]' and '[Application of action learning in BLP]'
--   became a quote block and a section title. The Rikkyo COB banner
--   image is vendored; the author's 200px headshot was dropped (too
--   small to render well, and the byline is in the text).
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0021',
    null,
    'resources/rikkyo-university-wial-global-award',
    'Rikkyo University Receives the WIAL Global Award in the Academic Sector',
    true,
    jsonb_build_object(
        'heroIntro', 'Rikkyo University''s Business Leadership Program was recognized at the Action Learning Global Forum in India for developing student leadership with Action Learning: 500 first-year students a year, faculty certified as coaches, and a culture of questions across the College of Business.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Published', 'value', 'Dec 2018'),
            jsonb_build_object('label', 'Author', 'value', 'Fumiyo Seimiya, WIAL Japan'),
            jsonb_build_object('label', 'Reading time', 'value', '3 min')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'An award for a distinctive approach',
                'image', '/resources/blog/rikkyo-college-of-business.jpg',
                'imageAlt', 'Rikkyo University College of Business banner on an ivy-covered building',
                'paragraphs', jsonb_build_array(
                    'The Business Leadership Program (BLP) at the College of Business (COB), Rikkyo University, was awarded at the Action Learning Global Forum in India for its distinctive approach that develops students'' leadership by using Action Learning. WIAL Japan reported this successful achievement.',
                    'Prof. Higano mentioned that by implementing Action Learning he was not only able to encourage students'' independence, but also to build up the culture at COB. He stressed the high evaluation the program is receiving even from outside the university: the COB''s activities were selected as an excellent model and as good practice for education by Japan''s Ministry of Education, Culture, Sports, Science and Technology (MEXT). A clear and important measurable indicator of the program''s success is that the COB''s evaluation and its graduates'' employment rate are on the rise. Prof. Higano received applause from the participants in the Global Forum, especially for illustrating his presentation in the Japanese style of utilizing videos.'
                )
            ),
            jsonb_build_object(
                'type', 'quote',
                'quote', 'I used the following metaphor in my presentation in Delhi. The status of BLP at COB at Rikkyo University was like parachuting down into the middle of people who do not understand the purpose of leadership education, barricading in a trench, and waiting for the main unit to advance, meaning the purpose of leadership education to be understood broadly. ''Leadership without authority'' was not popularized in Japan when we started the program. While being surrounded and not being able to escape (and not wanting to escape), one of the tunnels dug to resupply from faraway allies was Action Learning. With this approach, faculty and student assistants learned their function during project-based learning classes, and students learned leadership based on questions. This created a culture of feedback at COB. The advancement of the main unit happened around 2011. First, Rikkyo University received the Excellent Award from WIAL Japan. Winning an award from WIAL, I am very happy that patiently waiting in the trench has finally paid off.',
                'attribution', 'Prof. Higano, College of Business, Rikkyo University'
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'How Action Learning is applied in the Business Leadership Program',
                'paragraphs', jsonb_build_array(
                    'In the BLP, concepts and Action Learning sessions are integrated into activities, and professors and staff utilize their skills as Action Learning coaches in the classes. First, 500 newly enrolled students in COB experience Action Learning in the Welcome Camp, a one-day introductory orientation. By organizing Action Learning sessions in the Welcome Camp, team building and relationship building between the new and sophomore students is developed, allowing them to socialize easily. Secondly, Action Learning sessions are conducted in the middle of the term, when the project-based learning class is offered, to give students the opportunity to reflect on their activities as a team.',
                    'To support such programs, faculty and staff at COB entered the certified Action Learning coach program provided by WIAL Japan. Professors and staff utilize the questioning skills they learned in and out of the training courses. This has created active communication between students and faculty, some of them asking the typical Action Learning question "How can we do it better?" in the middle of class. As Prof. Higano presented, Action Learning is used at COB as a useful tool, and it has also contributed to building the culture at COB by sharing the importance of asking questions.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'About the author',
                'paragraphs', jsonb_build_array(
                    'Fumiyo Seimiya reported this story for WIAL Japan. It was first published in December 2018.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Rikkyo University is one of many organizations WIAL has recognized',
                'body', 'See every WIAL award category and the winners from past years.',
                'href', '/awards',
                'label', 'See the WIAL Awards'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore more Action Learning resources',
                'body', 'Case studies, books, videos, and hundreds of WIAL Talk coaching scenarios are gathered in the WIAL library.',
                'href', '/resources',
                'label', 'Back to the library'
            )
        )
    ),
    jsonb_build_object(
        'description', 'How Rikkyo University''s Business Leadership Program won the WIAL Global Award by building student leadership and a culture of questions with Action Learning.',
        'sourceUrl', 'https://wial.org/rikkyo-university-receives-wial-global-award-academic-sector/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from the sibling ''blog'' category (category/blog), which is not linked from the wial.org menu. Text is verbatim with light copy edits; the bracketed source headings ''[Comment by Prof. Higano]'' and ''[Application of action learning in BLP]'' became a quote block and a section title. The Rikkyo COB banner image is vendored; the author''s 200px headshot was dropped (too small to render well, and the byline is in the text).'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();

-- ============================================================
-- Migration: Upsert the "The Future Is Action Learning" page (slug: resources/the-future-is-action-learning)
-- Source: https://wial.org/future-action-learning-2/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated from the sibling 'blog' category (category/blog). The
--   speech text is verbatim with light copy edits; the closing lines
--   became a quote block. Both source images (a 1024x200 graduation
--   collage strip and a 300x200 photo of the speaker) were dropped
--   as too small or too wide for the article layout; the post has no
--   image, so link previews are text-only.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0022',
    null,
    'resources/the-future-is-action-learning',
    'The Future Is Action Learning',
    true,
    jsonb_build_object(
        'heroIntro', 'At the 2016 BSN graduation ceremony, Twan Paes MBA MALC was asked whether Action Learning has a future. His answer, in this speech to the new Action Learning MBAs: the future is Action Learning, as long as leaders keep working on the skills.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Published', 'value', 'Dec 2018'),
            jsonb_build_object('label', 'Author', 'value', 'Twan Paes'),
            jsonb_build_object('label', 'Reading time', 'value', '3 min')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'A graduation question',
                'paragraphs', jsonb_build_array(
                    'During the 2016 BSN graduation ceremony, Twan Paes, one of WIAL''s most experienced Action Learning trainers, addressed the question of whether there is a future for Action Learning. His statement is that "the future is Action Learning". Keeping and improving your Action Learning skills is key for the future performance of management, Mr. Paes concludes. His speech follows.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Is Action Learning still relevant?',
                'paragraphs', jsonb_build_array(
                    'Dear graduates, family, friends. Congratulations on obtaining your Action Learning MBA degree. Frank asked me: is there a future for Action Learning? That is a great question. Action Learning was developed in the 1950s. Is it still relevant today? Yes, it may even be more relevant than ever! Organizations increasingly have to cope with growing diversity and uncertainty.',
                    'Does Action Learning help to respond to that? And does it help us to create new opportunities? I really think so. Many organizations (and their leaders) have not yet found a successful and sustainable way of dealing with this uncertainty and diversity. We do not succeed by just managing the so-called upper stream. Therefore it is important to create an atmosphere in which all people feel appreciated and respected, as well as supported. These invisible aspects of the undercurrent require leadership skills. Action Learning involves attention to both the upper stream and the undercurrent. It also requires a balance in the roles of leader, coach and manager.',
                    'The power of Action Learning is that it contributes to the continuous process of achieving consensus on challenges and problems. It begins at an early stage! Let''s take primary school as an example. The great Action Learning question in this case is: "How do I prepare children for their unpredictable future?" This is absolutely different from the past, since we have always prepared people for a more predictable future. But the banking sector, industry and government should also keep asking these kinds of questions.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Three roles: leader, manager, coach',
                'paragraphs', jsonb_build_array(
                    'To reach agreement within a team, it takes Action Learning coaches who can speak about the problems. They also need to be able to make use of the power of differences in their team. Action Learning coaches need to be able to let others learn.',
                    'Recently, I was talking with a student who gave a striking example: despite his thorough preparation for implementing strategies, he was increasingly engaged with the diversity and emotions in the undercurrent. This was demanding for him. It required more than just knowledge of models and theories.',
                    'So, does Action Learning help us to create new opportunities and cope with increasing diversity? Yes, as long as you keep working on skills like problem analysis, dialogue, team building and giving feedback. Furthermore, it is important to realize three roles: leader, manager and coach. Leadership means having a vision and conveying inspiration to your employees. The manager sets targets, determines the strategy and makes adjustments. As a coach you motivate people to keep developing themselves as individuals, and to develop collaborative skills.',
                    'Is your MBA degree sufficient to do all that? No, it is just the start. What is ahead of you is lifelong learning. Keep curious and face the uncertain future. Action Learning is the key to success. I wish you all the best with your future challenges. You have all deserved your MBA degree, but in the future you all need to prove to be worth it.'
                )
            ),
            jsonb_build_object(
                'type', 'quote',
                'quote', 'Frank, you asked me: is there a future for Action Learning? No, the future is Action Learning! Graduates: enjoy this beautiful day and keep on Action Learning. The companies need you.',
                'attribution', 'Twan Paes MBA MALC, BSN graduation ceremony 2016'
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'About the speaker',
                'paragraphs', jsonb_build_array(
                    'Twan Paes is a Master Action Learning Coach (MALC) and one of WIAL''s most experienced Action Learning trainers. This speech was delivered at the 2016 graduation ceremony of Business School Netherlands (BSN), whose MBA is built on Action Learning, and published on wial.org in December 2018.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Explore more Action Learning resources',
                'body', 'Case studies, books, videos, and hundreds of WIAL Talk coaching scenarios are gathered in the WIAL library.',
                'href', '/resources',
                'label', 'Back to the library'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Twan Paes MBA MALC''s BSN graduation speech on why the future is Action Learning: coping with uncertainty, and the roles of leader, manager and coach.',
        'sourceUrl', 'https://wial.org/future-action-learning-2/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated from the sibling ''blog'' category (category/blog). The speech text is verbatim with light copy edits; the closing lines became a quote block. Both source images (a 1024x200 graduation collage strip and a 300x200 photo of the speaker) were dropped as too small or too wide for the article layout; the post has no image, so link previews are text-only.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
