-- ============================================================
-- Migration: Upsert the "Community Impact" page (slug: community-impact)
-- Source: https://wial.org/community-impact-infographic/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Consolidates two unlisted wial.org utility pages (#144):
--   /community-impact-infographic/ (a single Elementor image) and
--   /community-impact-video/ (a single YouTube embed), both linked
--   from the source Benefits page. The infographic's text was
--   transcribed into the hero intro, the prose section, and the
--   native comparison section (its two-column traditional-vs-WIAL
--   layout is what the comparison section type was added for) so it
--   is readable, searchable, and on-brand; the graphic itself is
--   vendored to public/community-impact/ as webp and offered as a
--   download. The source's 'Organizations focus on profit, being
--   best for the world' under Traditional approach is an obvious
--   typo for 'best in the world' and was corrected. The video is
--   embedded via youtube-nocookie from WIAL's own channel; the
--   YouTube link under Share the message is intentionally external.
--   The WIAL Gives Back photo is the vendored Be My Protector
--   Malaysia image already used by /better-world/malaysia-we-the-
--   protector. Both legacy paths alias-redirect here, /benefits
--   links here from its Community impact section, and the page is
--   deliberately not in the header nav.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0032',
    null,
    'community-impact',
    'Community Impact',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL helps to create a better world by supporting organizations that make a positive social impact. Through the delivery of pro bono coaching and grant funding to nonprofits, social enterprises, and other purpose-driven organizations, we contribute to positive outcomes globally.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Pro bono coaching', 'value', 'WIAL Gives Back'),
            jsonb_build_object('label', 'Grant funding', 'value', 'Better World Fund'),
            jsonb_build_object('label', 'Better World stories', 'value', '8')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Action Learning as a tool for community partnership',
                'paragraphs', jsonb_build_array(
                    'Action Learning is a powerful tool to create strong partnerships with community groups and is a great way to improve communities and lives globally.',
                    'When a nonprofit or community organization works on a real, urgent problem with a WIAL-certified coach, the team solves the problem and builds its own capacity at the same time. The questions-first process gives every member a voice, surfaces the root issue, and leaves the organization with leaders who can keep applying the method after the coach has gone.'
                )
            ),
            jsonb_build_object(
                'type', 'comparison',
                'title', 'Traditional approach vs. WIAL Action Learning',
                'description', 'How leadership development changes when community impact is the goal rather than a by-product.',
                'columns', jsonb_build_array(
                    'Traditional approach',
                    'WIAL Action Learning'
                ),
                'rows', jsonb_build_array(
                    jsonb_build_object(
                        'label', 'What is the purpose?',
                        'before', 'Organizations focus on profit, being ''best in the world''.',
                        'after', 'Organizations focus on being ''best for the world'' – being socially responsible.'
                    ),
                    jsonb_build_object(
                        'label', 'What is the focus of development?',
                        'before', 'Focus on individual leadership skills narrowly applied to the organization they serve.',
                        'after', 'Building the skills and behaviors that leaders need to support the wider society and community.'
                    ),
                    jsonb_build_object(
                        'label', 'How is society impacted?',
                        'before', 'Working in a silo and not in partnership with the wider society or community.',
                        'after', 'Leaders become more aware of the role they play in society and the communities they serve.'
                    ),
                    jsonb_build_object(
                        'label', 'What next?',
                        'before', 'Corporate social responsibility is a ''tick box'' exercise without making meaningful and sustainable change to the wider ecosystem.',
                        'after', 'Working in partnership with the community and society on real challenges and finding sustainable solutions that make a real difference in the lives of others.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'video',
                'title', 'Watch: Action Learning and community impact',
                'description', 'WIAL''s short video on how Action Learning creates community impact.',
                'videoUrl', 'https://www.youtube-nocookie.com/embed/gZFC1Vd8Bfo',
                'videoTitle', 'WIAL Action Learning Benefits: Community Impact',
                'caption', 'WIAL Action Learning Benefits: Community Impact, from WIAL''s YouTube channel.'
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'WIAL Gives Back in action',
                'image', '/better-world/stories/malaysia-we-the-protector.jpg',
                'imageAlt', 'WIAL Gives Back coaches and Be My Protector Malaysia team members celebrating together at an event in Kuala Lumpur',
                'imagePosition', 'right',
                'paragraphs', jsonb_build_array(
                    'Through WIAL Gives Back, certified coaches volunteer their time to run Action Learning sessions for nonprofits and community organizations — from hospital administrators and young entrepreneurs in Thailand to Red Cross societies, a deaf association in Singapore, and a human-rights platform in Malaysia.',
                    'The Better World Fund adds grant funding so that purpose-driven organizations can take part regardless of budget. Every project ends with a solution the team owns and a group of leaders who know how to keep asking the questions that matter.'
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'How WIAL creates community impact',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Pro bono coaching',
                        'title', 'WIAL Gives Back',
                        'body', 'Certified coaches donate Action Learning sessions to nonprofits, social enterprises, and community groups around the world.',
                        'href', '/better-world',
                        'label', 'About the initiative'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Grant funding',
                        'title', 'Better World Fund',
                        'body', 'Donations fund Action Learning support for purpose-driven organizations that could not otherwise afford it.',
                        'href', '/better-world/donate',
                        'label', 'Support the fund'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Real results',
                        'title', 'Better World stories',
                        'body', 'Read how organizations in Thailand, Singapore, Malaysia, Grenada, and beyond solved real problems with Action Learning.',
                        'href', '/better-world',
                        'label', 'Read the stories'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Get involved',
                        'title', 'Become a certified coach',
                        'body', 'WIAL-certified coaches carry the method into their own organizations and communities.',
                        'href', '/certification',
                        'label', 'Explore certification'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'resource_list',
                'title', 'Share the message',
                'description', 'Use WIAL''s community impact materials in your own organization or network.',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'kind', 'Infographic',
                        'title', 'Community Impact infographic',
                        'body', 'The traditional-versus-Action-Learning comparison above as a one-page graphic you can print or share.',
                        'href', '/community-impact/community-impact-infographic.webp',
                        'label', 'Open the infographic'
                    ),
                    jsonb_build_object(
                        'kind', 'Video',
                        'title', 'Community Impact on YouTube',
                        'body', 'Watch or share the WIAL Action Learning Benefits: Community Impact video from WIAL''s channel.',
                        'href', 'https://www.youtube.com/watch?v=gZFC1Vd8Bfo',
                        'label', 'Open on YouTube'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Know an organization that could use Action Learning?',
                'body', 'Nominate a nonprofit or community organization for Better World Fund support, or donate to help fund the next project.',
                'href', '/better-world/nominate',
                'label', 'Nominate an organization'
            )
        )
    ),
    jsonb_build_object(
        'description', 'How WIAL creates community impact: pro bono Action Learning coaching and Better World Fund grants for nonprofits and social enterprises, and how that differs from a traditional leadership-development approach.',
        'sourceUrl', 'https://wial.org/community-impact-infographic/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Consolidates two unlisted wial.org utility pages (#144): /community-impact-infographic/ (a single Elementor image) and /community-impact-video/ (a single YouTube embed), both linked from the source Benefits page. The infographic''s text was transcribed into the hero intro, the prose section, and the native comparison section (its two-column traditional-vs-WIAL layout is what the comparison section type was added for) so it is readable, searchable, and on-brand; the graphic itself is vendored to public/community-impact/ as webp and offered as a download. The source''s ''Organizations focus on profit, being best for the world'' under Traditional approach is an obvious typo for ''best in the world'' and was corrected. The video is embedded via youtube-nocookie from WIAL''s own channel; the YouTube link under Share the message is intentionally external. The WIAL Gives Back photo is the vendored Be My Protector Malaysia image already used by /better-world/malaysia-we-the-protector. Both legacy paths alias-redirect here, /benefits links here from its Community impact section, and the page is deliberately not in the header nav.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
