-- ============================================================
-- Migration: Upsert the "Privacy Policy" page (slug: privacy)
-- Source: https://wial.org/privacy-policy/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Migrated verbatim (aside from light punctuation normalization)
--   from wial.org/privacy-policy/ as 19 prose sections following the
--   source's own numbered headings; sections were split around
--   bulleted lists so list order matches the source. Two source
--   defects were corrected without changing wording: a run-on in the
--   'With whom we share' list that concatenated the Service
--   providers and Business partners bullets was split in two, and
--   '.2.' was corrected to '5.2.' in the 'How you can access your
--   information' section. The source also skips from section 9 to
--   section 11 (no section 10 exists on wial.org) and states an
--   Effective Date of January 15, 2020 despite the page being last
--   modified 2026-03-05 on wial.org; both are kept as-is. Legacy
--   references to cookies, web beacons, third-party ad networks, and
--   the Network Advertising Initiative opt-out are retained verbatim
--   though unverified against this platform's actual tracking (none
--   of our integrations — Stripe, Supabase, OpenRouter, Resend,
--   Credly — are named in the source text). The body repeatedly
--   lists service@wial.org as the privacy contact, which differs
--   from the footer's info@wial.org; both addresses are kept as
--   published. See the GitHub issue #122 comment for the full flag
--   list; this content needs legal review before being treated as
--   WIAL's authoritative policy.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0023',
    null,
    'privacy',
    'Privacy Policy',
    true,
    jsonb_build_object(
        'heroIntro', 'How WIAL collects, uses, and shares the personal information of coaches, affiliates, and other website visitors, and how to reach us with privacy questions.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Effective date', 'value', 'January 15, 2020')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Overview',
                'paragraphs', jsonb_build_array(
                    'The international World Institute for Action Learning ("WIAL") values its relationship with our coaches, affiliates, partners, clients and other website visitors (collectively, "Users" or "you") and respects our Users'' privacy. We have developed this Privacy Policy to describe how WIAL collects personal information of Users, how that information may be used, with whom it may be shared, and your choices about such uses and disclosures.',
                    'We encourage our Users to read this Privacy Policy carefully when using our website, services or otherwise transacting business with us (collectively, the "Services"). By using our Services, you are accepting the practices described in this Privacy Policy.',
                    'WIAL partners with a number of independent organizations approved by WIAL to promote action learning and related services in a specific country or geographic region (each, a "WIAL Affiliate"). To the extent you maintain a direct relationship with a WIAL Affiliate, the personal information that you provide to that WIAL Affiliate may be subject to that organization''s own privacy policy and terms.',
                    'If you have any questions about our privacy practices, please refer to the end of this Privacy Policy for information on how to contact us.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '1. Information we collect about you',
                'paragraphs', jsonb_build_array(
                    '1.1. In General. We collect a few categories of information from and about you for the purposes described in this policy. Some of the information we collect may identify you and may not be publicly available. We may collect information directly from you or from others. When you provide personal information through our website, the information may be sent to servers located in the United States and other countries around the world.',
                    'Information you provide. We may collect and store personal information that you submit through our website or provide to us in some other manner. This includes identifying information, such as your name, address, e-mail address, and telephone number, and in addition, for Coaches, your photo, company, title, website address, curriculum vitae or brochure, affiliation, credentials, bio, and payment information. We may also request information about your interests and activities, gender, age, and other demographic information.',
                    'Information from WIAL Affiliates. We may also receive the information listed above from WIAL Affiliates, such as for posting information about Coaches on our WIAL Directory and other services to Coaches, partners, clients and other third parties.',
                    'Information from other sources. We may also receive personal information about you from other business partners, contractors, and other third parties. Examples of information that we may receive include (but are not limited to) updated delivery and address information, purchase history, and additional demographic information.',
                    'Information about others. We may also collect and store personal information about other individuals that you provide to us. If you use our website to send others (friends, relatives, colleagues, etc.) information, we may store your personal information and the personal information of each such recipient. If you provide us with information regarding another individual, you represent that you have that person''s consent to give us that information and to permit us to use the information in accordance with this Privacy Policy.',
                    '1.2. Use of cookies and other technologies. When you visit our website, open an email that we send you, or interact with us through social media platforms, we may collect information about you or your activities on our Services by automated means. In some instances, we may also allow third party advertisers and service providers to collect information about you through automated means.',
                    'Information collected automatically. We automatically collect information from your browser when you visit our Services. This information can include your IP address, browser type, language, access times, the content of any undeleted cookies that your browser previously accepted from us (see below) and the referring website address.',
                    'When you visit our Services, we may assign your computer one or more cookies to facilitate access to our site and to personalize your online experience. Through the use of a cookie, we also may automatically collect information about your online activity on our Services, such as the web pages you visit, the links you click, and the searches you conduct. Most browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies. If you choose to decline cookies, please note that you may not be able to sign in or use some of the interactive features offered on our website.',
                    'We may use other common internet technologies, such as web beacons (i.e., pixels) and other similar technologies to track your activity while using our Services. We may also include web beacons or the like in promotional or other e-mail messages or newsletters to determine whether messages have been opened and acted upon. The information we collect this way allows us to customize the services we offer to Users of our Services, deliver targeted advertisements, and to measure the overall effectiveness of our online advertising, content, programming or other activities. Please see the end of this Privacy Policy for more information about cookies and web beacons.',
                    'At this time, we do not monitor for "do not track" signals from any website browsers and handle all personal information pursuant to this Privacy Policy.',
                    'Information collected by third parties. We may allow third parties, including (but not limited to) our authorized service providers, advertising companies, and ad networks, to display advertisements through our Services. These companies may use tracking technologies, such as cookies, to collect information about users who view or interact with their advertisements. Our Services do not provide any personal information to these third parties, however, such website activity information could potentially be used by those vendors for their own purposes, some of whom may be able to associate such information with you based on other information they have collected independently (not from us). This information allows them to deliver targeted advertisements and gauge their effectiveness. Some of these third-party advertising companies may be advertising networks that are members of the Network Advertising Initiative, which offers a single location to opt-out of ad targeting from member companies (networkadvertising.org).'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '2. How we use the information we collect',
                'paragraphs', jsonb_build_array(
                    'In General. We may use information that we collect about you to:'
                ),
                'bullets', jsonb_build_array(
                    'Deliver the products and services that you have requested, including management of your account and providing customer support;',
                    'Perform research and analysis about your use of, or interest in, our products, services, or content, or products, services or content offered by others;',
                    'Communicate with you through our Services including e-mail, postal mail, and telephone with information or newsletters about products or services that may be of interest to you either from us or other third parties;',
                    'Develop and display content and advertising tailored to your interests on our Services and other sites;',
                    'Perform background screening on Coaches, if applicable, including through third parties;',
                    'Operate and improve our business and operations, including internal administration, auditing and troubleshooting for our Services;',
                    'As we believe to be necessary or appropriate for certain essential purposes, such as to (i) comply with applicable law and legal process, (ii) detect, prevent, or investigate potential security or fraud events, (iii) enforce our Terms of Use, (iv) protect our operations or those of WIAL Affiliates, (v) protect our rights, privacy, safety or property, security and/or that of WIAL Affiliates, our business partners, you or others, and (vi) allow us to pursue available remedies or limit the damages that we may sustain; and',
                    'Perform functions as otherwise described to you at the time of collection.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Financial information, job applicants and anonymized data',
                'paragraphs', jsonb_build_array(
                    '2.2. Financial information. For Coaches and other partners, we may use financial information or payment method to process payments for any purchases made through our Services, enroll you in discount, rebate, and other programs in which you elect to participate, to pre-qualify Coaches to participate in our directory service, to protect against or identify possible fraudulent transactions, and otherwise as reasonably needed to provide the Services to you.',
                    '2.3. Job applicants. If your personal information is submitted through our Services when applying for a position with us, the information will be used solely in connection with considering and acting upon your application. We may retain your personal information for a period of time, but only for the purpose of considering your application for current or future available positions. This information may be shared with our other companies for the purpose of evaluating your qualifications for the particular position or other available positions, as well as with third-party service providers retained by us to collect, maintain and analyze candidate submissions for job postings.',
                    '2.4. Anonymized Information. We may also use or share your information in an anonymized manner that does not identify you ("Anonymized Information") for any purposes in our discretion, such as research, analysis, modeling, marketing, and advertising, as well as improvement of our Services. Our use of anonymized information is not subject to this Privacy Policy.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '3. With whom we share your information',
                'paragraphs', jsonb_build_array(
                    '3.1. In General. We want you to understand when and with whom we may share the personal information we have collected. We do not share your personal information with others except as indicated here or when we otherwise notify you and give you an opportunity to opt-out of having your personal information shared. We may share personal information with:'
                ),
                'bullets', jsonb_build_array(
                    'Service providers. We may share your personal information with our service providers that perform certain services on our behalf. These services may include fulfilling orders, processing credit card payments, delivering products or services, providing customer service and marketing assistance, performing business and sales analysis, supporting our website functionality, and other features offered through our Services or performing background checks of Coaches. These service providers may have access to personal information as needed to perform their functions but are not permitted to share or use such information for any other purposes. We may also release information to collection and/or credit agencies for past due accounts of Coaches and other business partners.',
                    'Business partners. We may share personal information with businesses with which we partner to offer you certain products or services at your direction. For example, when you elect to engage in a particular business''s offer or program, you authorize us to provide your email address and other information to that business.',
                    'Coaches and WIAL Affiliates. When requested, we try to match your information and service request with suitable Coaches or WIAL Affiliates. When you submit a request through our Services, you consent to our providing your personal information and request to the Coaches or WIAL Affiliates we match with your request. Sharing this information with Coaches or WIAL Affiliates allows them to contact you using the e-mail address or other contact information you provided. If using our Services pursuant to a membership with one of our partners, we may share your service request information with that partner.',
                    'Direct mail partners. From time to time we may share our postal mailing list with selected providers of goods and services that may be of interest to you. If you prefer not to have us share your postal mailing information with these selected providers, you can notify us at any time by emailing us at service@wial.org.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Publicly sharing Coach and Affiliate information',
                'paragraphs', jsonb_build_array(
                    '3.2. Publicly on our website and other outlets for Coach and WIAL Affiliate information. For Coaches, we may publicly share your business contact information, photo, company, title, website, curriculum vitae or brochure, affiliation, credentials, and bio through our Services online and offline so you can promote yourself as a Coach and member of the WIAL community. Likewise, we publicly share business contact information and related details of WIAL Affiliates and Partners as part of the WIAL community.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Other situations where we may disclose your information',
                'paragraphs', jsonb_build_array(
                    '3.3. Other Situations. We also may disclose your information in our discretion:'
                ),
                'bullets', jsonb_build_array(
                    'As legally necessary: (i) in response to a subpoena or similar investigative demand, court order, or request for cooperation from law enforcement or other government agency; (ii) to establish or exercise our legal rights; (iii) to defend against legal claims; or (iv) as otherwise required by law.',
                    'When we believe disclosure is appropriate: (i) in connection with efforts to investigate, prevent, or take other action regarding illegal activity, suspected fraud or other wrongdoing; (ii) to protect and defend the rights, property or safety of our company, our users, our employees, or others; or (iii) to enforce our website terms of use or other agreements or policies applicable to you.',
                    'In connection with a substantial corporate transaction, such as the sale of our business, a divestiture, merger, consolidation, or asset sale, or in the unlikely event of bankruptcy.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Third-party policies and aggregated information',
                'paragraphs', jsonb_build_array(
                    '3.4. Third-Party Policies. Any third parties to whom we may disclose personal information may have their own privacy policies which describe how they use and disclose personal information. Those policies will govern the use, handling and disclosure of your personal information once we have shared it with those third parties as described in this Privacy Policy. If you want to learn more about their privacy practices, we encourage you to visit the websites of those third parties. These entities or their servers may be located either inside or outside the United States.',
                    '3.5. Aggregated and non-personal information. As noted above, we may share Anonymized Information we collect under any circumstances in our discretion, including with advisors, investors, for the purpose of conducting general business analysis, or with advertisers to deliver targeted advertising through our Services or on the websites of third parties. We may combine Anonymized Information originating from your personal information with other Anonymized Information from other sources.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '4. Third-party websites',
                'paragraphs', jsonb_build_array(
                    'There are a number of places on our website where you may click on a link to access other websites that do not operate under this Privacy Policy. For example, if you click on the link for a Coach, WIAL Affiliate, WIAL Partner, advertisement or a search result on our website, you may be taken to a website that we do not control. These third-party websites may independently solicit and collect information, including personal information, from you and, in some instances, provide us with information about your activities on those websites. We recommend that you consult the privacy statements of all third-party websites you visit by clicking on the "privacy" link typically located at the bottom of the webpage you are visiting.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '5. How you can access your information',
                'paragraphs', jsonb_build_array(
                    '5.1. If you have an online account with us, you have the ability to review and update your personal information online by logging into your account. You can also review and update your personal information by contacting us. Information on how to contact us is provided below. Note that certain changes (such as affiliates and certifications) may be subject to our review and approval.',
                    '5.2. You can also choose to have your account disabled by contacting service@wial.org. After you deactivate your account, you will not be able to access your account or personal information. However, you can open a new account at any time, subject to our review and approval. If you deactivate your account, we may still retain certain information associated with your account for analytical purposes and recordkeeping integrity, as well as to prevent fraud, collect any fees owed, enforce our terms of use and other policies, take actions we deem necessary to protect the integrity of our Services, or take other actions otherwise permitted by law. In addition, if certain information has already been provided to third parties as described in this Privacy Policy, retention of that information will be subject to those third parties'' policies.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '6. Your choices about collection and use of your information',
                'paragraphs', jsonb_build_array(
                    '6.1. You can choose not to provide us with certain information, but that may result in you being unable to use certain features of our Services because such information may be required in order for you to register as a member of our directory service, use our Services, purchase products or services, participate in a survey, ask a question, or perform other related transactions.',
                    '6.2. At any time, a user can choose to no longer receive commercial or promotional emails or newsletters from us by adjusting preferences within a User account or by opting out of receiving such messages in the future through the link provided in any commercial e-mail that we send to the User. It may take up to 10 days for us to process an opt-out request. We may send you other types of transactional and relationship e-mail communications, such as service announcements, administrative notices, and surveys, irrespective of a request to opt-out of marketing-related communications.',
                    '6.3. If you prefer not to have us share your postal mailing information with these selected providers of goods and services that may be of interest to you, you can notify us at any time by emailing us at service@wial.org.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '7. How we protect your personal information',
                'paragraphs', jsonb_build_array(
                    'We only keep your personal data for as long as we actually need it to provide Services to you and for reasonable business or legal purposes as described herein. We take appropriate security measures (including physical, electronic and procedural measures) designed to help safeguard your personal information from unauthorized access and disclosure. For example, only authorized employees are permitted to access personal information, and they may do so only for permitted business functions.',
                    'We want you to feel confident using our website to transact business. However, no system can be completely secure. Therefore, although we take steps to secure your information, we do not promise, and you should not expect, that your personal information, searches, or other communications will always remain secure.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '8. Blogs, bulletin boards, reviews and chat rooms',
                'paragraphs', jsonb_build_array(
                    'In the event we choose to provide areas on our Services where you can publicly post information about yourself and others and communicate with others, as well as post comments or upload content (e.g. pictures, etc.), such information will be governed by our Terms of Use. This information may appear on other websites or when searches are executed on the subject of your information. Also, whenever you voluntarily disclose personal information on publicly-viewable web pages, that information will be publicly available and can be collected and used by others. For example, if you post your email address, you may receive unsolicited messages. We cannot control who reads your posting or what others may do with information that you voluntarily post, so we encourage you to exercise discretion and caution with respect to your personal information. Once you have posted information, you may not be able to edit or delete such information.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '9. Children’s privacy',
                'paragraphs', jsonb_build_array(
                    'Our website is a general audience site, and we do not knowingly collect personal information from children under the age of 13. If you believe that a person under the age of 13 has provided us with his or her personal information, please let us know at service@wial.org.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '11. No rights of third parties',
                'paragraphs', jsonb_build_array(
                    'This Privacy Policy does not create rights enforceable by third parties or require disclosure of any personal information relating to users of the website.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '12. Effective date, and changes to this Privacy Policy',
                'paragraphs', jsonb_build_array(
                    'The Effective Date of this policy is January 15, 2020. We will occasionally update this Privacy Policy to reflect changes in our practices and Services. We recommend that you check our website from time to time to inform yourself of any changes in this Privacy Policy or any of our other policies.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '13. How to contact us',
                'paragraphs', jsonb_build_array(
                    'If you have any questions about this Privacy Policy or our information-handling practices, or if you would like to request information about our disclosure of personal information to third parties for their direct marketing purposes, please contact us by e-mail at service@wial.org or by postal mail to: P.O. Box 7601 #83791, Washington, DC 20044.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '14. Country-specific disclosures',
                'paragraphs', jsonb_build_array(
                    '14.1. For Canadian Users. Please note that your rights under applicable law to access your personal information are not absolute and we may deny access when required by law, when granting you access would have an unreasonable impact on other people''s privacy, to protect our rights and property, or where the request is frivolous or vexatious. If we deny your request for access to or refuse a request to correct personal information, we will explain why. We may provide information in a standardized format that is not specific to you. The designated email address for these requests is service@wial.org.',
                    '14.2. For European Users. European Union, European Economic Area and Switzerland residents (collectively "EU Users") can exercise legal rights pertaining to personal information by submitting a written request to us at service@wial.org at any time. Please mark your email "Data Subject Request" and indicate which of the following right(s) you are requesting: (i) identification of the personal information we have about you; (ii) prevent your personal information being used for marketing purposes; (iii) have inaccurate personal information corrected, blocked or erased; (iv) object to decisions being made about you by automated means or to your personal information being used for profiling purposes; (v) object to our using your personal information in ways that are likely to cause you damage or distress; (vi) restrict our use of your personal information; (vii) have your personal information deleted, or (viii) receive a copy of the personal information that we retain about you. After we verify your identity, any such requests will be processed as required by law subject to any applicable exceptions or other considerations permitted by law.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', '15. More information about cookies and web beacons (pixels)',
                'paragraphs', jsonb_build_array(
                    '15.1. Cookies: A cookie is a small text file that is stored on a user''s computer for record-keeping purposes. Cookies can be either session cookies or persistent cookies. A session cookie expires when you close your browser and is used to make it easier for you to navigate our website. A persistent cookie remains on your hard drive for an extended period of time.',
                    'For example, when you sign in to our website, we will record your user or member ID and the name on your user or member account in the cookie file on your computer. We also may record your password in this cookie file, if you indicated that you would like your password saved for automatic sign-in. For security purposes, we will encrypt any usernames, passwords, and other user or member account-related data that we store in such cookies. In the case of sites and services that do not use a user or member ID, the cookie will contain a unique identifier. We may allow our authorized service providers to serve cookies from our website to allow them to assist us in various activities, such as doing analysis and research on the effectiveness of our site, content, and advertising.',
                    'You may delete or decline cookies by changing your browser settings. (Click "Help" in the toolbar of most browsers for instructions.) If you do so, some of the features and services of our website may not function properly.',
                    'We may allow third parties, including advertising companies and ad networks, to display advertisements on our site. These companies may use tracking technologies, such as cookies, to collect information about users who view or interact with their advertisements. Our website does not provide any personal information to these third parties, but they may collect information about where you, or others who are using your computer, saw and/or clicked on the advertisements they deliver, and possibly associate this information with your subsequent visits to the advertised websites. They also may combine this information with personal information they collect from you. The collection and use of that information are subject to the third party''s privacy policy. This information allows them to deliver targeted advertisements and gauge their effectiveness. Some of these third-party advertising companies may be advertising networks that are members of the Network Advertising Initiative, which offers a single location to opt-out of ad targeting from member companies (networkadvertising.org).',
                    '15.2. Web Beacons: Web beacons (also known as clear gifs, pixels, tags or web bugs) are small pieces of computer code running on a webpage with a unique identifier that can be used along or in conjunction with cookies to track the online movements of web users. Unlike cookies which are stored on the user''s computer hard drive, web beacons are embedded on the web pages (or in email). Web beacons may be used to deliver or communicate with cookies, to count users who have visited certain pages and to understand usage patterns. We also may receive an anonymous identification number if you visit our Services from an online advertisement displayed on a third-party website.'
                )
            )
        )
    ),
    jsonb_build_object(
        'description', 'WIAL''s privacy policy: what personal information we collect from coaches, affiliates, and visitors, how it''s used and shared, and how to contact us about it.',
        'sourceUrl', 'https://wial.org/privacy-policy/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Migrated verbatim (aside from light punctuation normalization) from wial.org/privacy-policy/ as 19 prose sections following the source''s own numbered headings; sections were split around bulleted lists so list order matches the source. Two source defects were corrected without changing wording: a run-on in the ''With whom we share'' list that concatenated the Service providers and Business partners bullets was split in two, and ''.2.'' was corrected to ''5.2.'' in the ''How you can access your information'' section. The source also skips from section 9 to section 11 (no section 10 exists on wial.org) and states an Effective Date of January 15, 2020 despite the page being last modified 2026-03-05 on wial.org; both are kept as-is. Legacy references to cookies, web beacons, third-party ad networks, and the Network Advertising Initiative opt-out are retained verbatim though unverified against this platform''s actual tracking (none of our integrations — Stripe, Supabase, OpenRouter, Resend, Credly — are named in the source text). The body repeatedly lists service@wial.org as the privacy contact, which differs from the footer''s info@wial.org; both addresses are kept as published. See the GitHub issue #122 comment for the full flag list; this content needs legal review before being treated as WIAL''s authoritative policy.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
