-- ============================================================
-- Migration: Upsert the "Action Learning Resources" page (slug: resources)
-- Source: https://wial.org/action-learning/library/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Consolidates wial.org/wial-talk/, /action-learning/library/ (and
--   its books, video-and-podcasts, posters-infographics, and
--   articles sub-pages), /wial-endorsed-products/, and two orphan
--   PDFs (Power_of_Action_Learning.pdf, WIAL-Action-Learning-
--   Brochure-1.pdf, vendored to public/resources/). The Library and
--   WIAL Talk are data-driven rather than fixture sections:
--   scripts/crawl-wial-library.ts reads the WordPress REST API (the
--   rendered library page is polluted with injected SEO-spam
--   anchors, which are stripped) and scripts/import-library.ts re-
--   hosts every PDF/MP3/poster and thumbnail to the resource-files
--   bucket and upserts library_items (fixture fallback
--   src/content/library.json). Data decisions: 182 article posts ->
--   181 (the WIAL Thailand case-study PDF is a 404 at the source;
--   'solution-spheres' has no PDF); 8 video posts whose only content
--   was a thumbnail with no embedded video were dropped; SHOUTING-
--   CAPS titles were normalized to title case;
--   'Poster'/'Infographic' title prefixes removed because the kind
--   is shown separately. WIAL Talk: 624 weekly posts (2011-2026)
--   deduplicated on prompt text to 335 distinct scenarios in
--   src/content/wial-talk-scenarios.json; the member login and
--   discussion threads behind wial-talk are not public and were not
--   migrated. Endorsed products: four items with vendored images;
--   the decorative 'endorsed' badge graphic was dropped; the
--   guidelines PDF and application DOCX were on a broken /wial/wp-
--   content path on the source and were recovered from /wp-content;
--   author contact emails are those published on the source page;
--   the DREAM & DARE link goes to the product's own shop (mgtstrat-
--   shop.com), not wial.org. The five WIAL Blog posts
--   (category/wial-blog plus the unlinked category/blog) are
--   separate content pages under resources/<slug> (see #121); the
--   'From the WIAL Blog' grid links to them.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0017',
    null,
    'resources',
    'Action Learning Resources',
    true,
    jsonb_build_object(
        'heroIntro', 'Case studies, articles, books, videos, podcasts, posters, and hundreds of coaching scenarios from the WIAL community, gathered in one place. Everything here was published or endorsed by WIAL, and every file is hosted by WIAL so it stays available.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Library resources', 'value', '200+'),
            jsonb_build_object('label', 'Coaching scenarios', 'value', '300+'),
            jsonb_build_object('label', 'Endorsed products', 'value', '4')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'From the WIAL Blog',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Sep 2022 · Peter Cauwelier',
                        'title', 'Culture Change? Not Without Action Learning',
                        'body', 'Change programs redesign offices and rewrite values, but rarely reach the unspoken assumptions that guide behavior. Why Action Learning belongs inside every change initiative.',
                        'href', '/resources/culture-change-not-without-action-learning',
                        'label', 'Read the article'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Sep 2022 · Christoph Maria Ravesloot',
                        'title', 'Action Learning and Personal Leadership',
                        'body', 'Psychological safety, reflection, and the four reasons people find it hard to ask open questions.',
                        'href', '/resources/action-learning-and-personal-leadership',
                        'label', 'Read the article'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Jun 2022 · Peter Cauwelier',
                        'title', 'A Fresh Look at Ground Rule #1',
                        'body', 'There is no such thing as a long question. Why a WIAL coach should intervene after fifteen seconds.',
                        'href', '/resources/action-learning-ground-rule-1',
                        'label', 'Read the article'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Dec 2018 · Fumiyo Seimiya',
                        'title', 'Rikkyo University Receives the WIAL Global Award in the Academic Sector',
                        'body', 'How a Japanese business school built student leadership and a culture of questions with Action Learning.',
                        'href', '/resources/rikkyo-university-wial-global-award',
                        'label', 'Read the article'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Dec 2018 · Twan Paes',
                        'title', 'The Future Is Action Learning',
                        'body', 'A graduation speech on coping with uncertainty and balancing the roles of leader, manager, and coach.',
                        'href', '/resources/the-future-is-action-learning',
                        'label', 'Read the article'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'resource_list',
                'title', 'Guides and brochures',
                'description', 'Two short introductions to WIAL Action Learning to share with colleagues and clients.',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'kind', 'PDF · 2 pages',
                        'title', 'WIAL Action Learning Brochure',
                        'body', 'A two-page overview of the WIAL Action Learning process, its six components, the five outcome areas it delivers, and testimonials from Google, AirAsia, and the Grenada Red Cross.',
                        'href', '/resources/wial-action-learning-brochure.pdf',
                        'label', 'Download the brochure'
                    ),
                    jsonb_build_object(
                        'kind', 'PDF · 13 pages',
                        'title', 'The Power of Action Learning',
                        'body', 'Dr. Bea Carson''s paper on how an Action Learning coach''s early, process, and group-dynamic interventions turn a problem-solving session into lasting team learning.',
                        'href', '/resources/power-of-action-learning.pdf',
                        'label', 'Read the paper'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'WIAL endorsed products and services',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Certification program',
                        'title', 'TEAM.AS.ONE Team Psychological Safety Practitioner Certification',
                        'body', 'Based on the Team Psychological Safety model developed by Professor Amy Edmondson of Harvard University, which showed that psychological safety drives team learning and, in turn, team performance. The program examines the seven elements and five foundations of team psychological safety, uses a survey and report to assess a team''s level, and equips practitioners with tools and techniques, including WIAL Action Learning, to design a program that strengthens the elements that need it most. Program author: Peter Cauwelier.',
                        'href', 'mailto:peter@teamasone.com',
                        'label', 'Email Peter Cauwelier',
                        'image', '/resources/endorsed/team-as-one-psychological-safety-model.png',
                        'imageAlt', 'Diagram of the TEAM.AS.ONE team psychological safety model'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Book · Éditions Ellipses, Paris, 2020 · 165 pages',
                        'title', 'Développer l''Intelligence Collective : la méthode Action Learning',
                        'body', 'Daniel Belet''s in-depth look at WIAL Action Learning as a team-coaching approach that harnesses collaborative intelligence. Readers discover what the methodology is and isn''t, its principles, rules, and components, and how it can transform organizations. A clear, complete manual for anyone interested in an original and highly effective problem-solving and team-building approach.',
                        'href', 'mailto:drbelet@wanadoo.fr',
                        'label', 'Email Daniel Belet',
                        'image', '/resources/endorsed/developper-l-intelligence-collective.jpg',
                        'imageAlt', 'Cover of Développer l''Intelligence Collective by Daniel Belet'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Card game',
                        'title', 'DREAM & DARE: Stories and Conversations to Unleash Purpose, Powers, and Passions',
                        'body', 'More than a card game, DREAM & DARE uses the power of questions to generate stories and conversations toward self-discovery and deeper human connection. Story prompts explore five themes: do what you love, reach for your aspirations, embrace your inspiration, activate your greatness, and make work meaningful. Play solo, in pairs, or in groups of two to eight at family gatherings, team meetings, leadership workshops, and coaching sessions. Each set includes 60 DREAM cards, five instruction cards, a two-sided play mat, and two dice.',
                        'href', 'https://mgtstrat-shop.com',
                        'label', 'Order a set',
                        'image', '/resources/endorsed/dream-and-dare.jpg',
                        'imageAlt', 'The DREAM & DARE card game box and contents'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Book · Jandaíra, 2023 · 367 pages',
                        'title', 'Dialogue and Connection: How Action Learning Can Meet the Most Urgent Needs of the 21st Century',
                        'body', 'Magali Lopes explores the essential characteristics of human nature which, when sharpened and provoked, regenerate relationships and generate more connection, collaboration, and innovation. She presents an agile method for problem solving and learning that works across organizations, communities, and families: relying on dialogue and powerful questions leads to the rediscovery of problems, a curious look at differences, a mindset of continuous development, and more robust teams that face challenges without fear.',
                        'href', 'mailto:magali@8dialogos.com.br',
                        'label', 'Email Magali Lopes',
                        'image', '/resources/endorsed/dialogue-and-connection.jpg',
                        'imageAlt', 'Cover of Dialogue and Connection by Magali Lopes'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'resource_list',
                'title', 'Get your product or service endorsed',
                'description', 'WIAL endorses products and services that give coaches and practitioners reliable resources and training aligned with WIAL standards, so the community has access to trustworthy tools and opportunities for continuous learning. Read the guidelines first, then complete the application form and send it to WIAL.',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'kind', 'PDF · 9 pages',
                        'title', 'WIAL Endorsement Guidelines (2024)',
                        'body', 'What WIAL looks for in an endorsed product or service, how applications are assessed, and what endorsement gives you.',
                        'href', '/resources/endorsed/wial-endorsement-guidelines-2024.pdf',
                        'label', 'Read the guidelines'
                    ),
                    jsonb_build_object(
                        'kind', 'Word document',
                        'title', 'WIAL Endorsement Application Form (2024)',
                        'body', 'The application to complete once you have read the guidelines.',
                        'href', '/resources/endorsed/wial-endorsement-application-form-2024.docx',
                        'label', 'Download the application form'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Provider, product, and service disclaimer',
                'paragraphs', jsonb_build_array(
                    'Information about the providers, products, and services endorsed by the World Institute for Action Learning reflects the decision of the WIAL Board and/or Endorsement Committee and does not represent the opinion of the entire WIAL community. Endorsement is based on an assessment of the provider, product, or service and its contribution to the body of knowledge or professional practice of WIAL Action Learning. Any proceeds from WIAL Global''s endorsements will not be used to support any political, religious, or cultural affiliation, and WIAL Global does not preclude authors from supporting their own causes. Readers are responsible for verifying the affiliations of the authors and providers offering products and services.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Have a resource to share?',
                'body', 'Coaches and affiliates publish case studies, articles, and videos through WIAL. Get in touch to propose one for the library.',
                'href', '/contact',
                'label', 'Contact WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Books, articles, case studies, videos, podcasts, posters, and WIAL Talk coaching scenarios from the World Institute for Action Learning.',
        'sourceUrl', 'https://wial.org/action-learning/library/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Consolidates wial.org/wial-talk/, /action-learning/library/ (and its books, video-and-podcasts, posters-infographics, and articles sub-pages), /wial-endorsed-products/, and two orphan PDFs (Power_of_Action_Learning.pdf, WIAL-Action-Learning-Brochure-1.pdf, vendored to public/resources/). The Library and WIAL Talk are data-driven rather than fixture sections: scripts/crawl-wial-library.ts reads the WordPress REST API (the rendered library page is polluted with injected SEO-spam anchors, which are stripped) and scripts/import-library.ts re-hosts every PDF/MP3/poster and thumbnail to the resource-files bucket and upserts library_items (fixture fallback src/content/library.json). Data decisions: 182 article posts -> 181 (the WIAL Thailand case-study PDF is a 404 at the source; ''solution-spheres'' has no PDF); 8 video posts whose only content was a thumbnail with no embedded video were dropped; SHOUTING-CAPS titles were normalized to title case; ''Poster''/''Infographic'' title prefixes removed because the kind is shown separately. WIAL Talk: 624 weekly posts (2011-2026) deduplicated on prompt text to 335 distinct scenarios in src/content/wial-talk-scenarios.json; the member login and discussion threads behind wial-talk are not public and were not migrated. Endorsed products: four items with vendored images; the decorative ''endorsed'' badge graphic was dropped; the guidelines PDF and application DOCX were on a broken /wial/wp-content path on the source and were recovered from /wp-content; author contact emails are those published on the source page; the DREAM & DARE link goes to the product''s own shop (mgtstrat-shop.com), not wial.org. The five WIAL Blog posts (category/wial-blog plus the unlinked category/blog) are separate content pages under resources/<slug> (see #121); the ''From the WIAL Blog'' grid links to them.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
