-- ============================================================
-- Migration: Upsert the "World Institute for Action Learning" page (slug: home)
-- Source: https://wial.org/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live wial.org homepage (Action Learning,
--   Solution Spheres, Benefits, People/coach directory,
--   Certification pillars, Better World Fund spotlight, newsletter
--   signup). All five What WIAL offers cards link internally
--   (/action-learning, /our-services, /benefits, /coaches,
--   /certification).
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0001',
    null,
    'home',
    'World Institute for Action Learning',
    true,
    jsonb_build_object(
        'heroIntro', 'WIAL is the world''s leading certifying body for Action Learning — a way of thinking, doing business, and working in teams that helps organizations solve real problems while developing their people at the same time.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Certification levels', 'value', '4'),
            jsonb_build_object('label', 'Solution categories', 'value', '4'),
            jsonb_build_object('label', 'Global affiliates', 'value', '8')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'statements',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'label', 'Purpose',
                        'body', 'We transform ambitious organizations into places of continuous learning, making them capable of solving today’s challenges and embracing the opportunities of tomorrow through the promotion and practice of action learning.'
                    ),
                    jsonb_build_object(
                        'label', 'Vision',
                        'body', 'We believe that ambitious organizations need new ways of thinking, doing business, and collaborating to solve their complex problems and achieve their desired results.'
                    ),
                    jsonb_build_object(
                        'label', 'Mission',
                        'body', 'WIAL coaches elevate team performance through action learning. They support teams in identifying breakthrough solutions to real problems, while accelerating individual, team and organizational development. WIAL’s team coaching leads to more effective organizations, positive business impact and a learning culture.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'What WIAL offers',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Action Learning',
                        'title', 'What is Action Learning?',
                        'body', 'A structured approach to solving urgent, real problems while building leadership and teamwork skills at the same time.',
                        'href', '/action-learning',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Solution Spheres',
                        'title', 'Action Learning solutions for your business',
                        'body', 'WIAL offers Action Learning solutions that help individuals, teams, and organizations grow.',
                        'href', '/our-services',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Benefits',
                        'title', 'Get more out of your business',
                        'body', 'See how Action Learning benefits individuals, teams, and organizations.',
                        'href', '/benefits',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'People',
                        'title', 'Search for Action Learning coaches',
                        'body', 'Find WIAL-certified coaches through the WIAL coach directory.',
                        'href', '/coaches',
                        'label', 'Read more'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Certification',
                        'title', 'The world''s leading certifying body for Action Learning',
                        'body', 'Action Learning changes the way individuals and organizations work, think, and do business.',
                        'href', '/certification',
                        'label', 'Read more'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'WIAL Better World Fund',
                'body', 'Established in 2015 to bring Action Learning services to community-based organizations around the world.',
                'href', '/better-world',
                'label', 'Learn more'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Join our newsletter',
                'body', 'Stay up to date on everything happening in Action Learning — never miss a beat.',
                'href', 'https://visitor.r20.constantcontact.com/d.jsp?llr=h87lpjrab&p=oi&m=1118083347303&sit=hbv7bh5ib&f=bd24fab6-ed5e-45b8-8360-2459192c640b',
                'label', 'Sign up'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Questions about WIAL or Action Learning?',
                'body', 'Contact us with certification questions or to learn how to get involved with a WIAL affiliate near you.',
                'href', '/contact',
                'label', 'Talk with WIAL'
            )
        )
    ),
    jsonb_build_object(
        'description', 'Global WIAL homepage content migrated from the live wial.org homepage.',
        'sourceUrl', 'https://wial.org/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live wial.org homepage (Action Learning, Solution Spheres, Benefits, People/coach directory, Certification pillars, Better World Fund spotlight, newsletter signup). All five What WIAL offers cards link internally (/action-learning, /our-services, /benefits, /coaches, /certification).'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
