-- ============================================================
-- Migration: Upsert the "About WIAL" page (slug: about)
-- Source: https://wial.org/about-us/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Full content migrated from wial.org/about-us/ with Better World
--   Fund, Conferences, and Awards links added (Awards now internal
--   at /awards). Leadership consolidated from wial.org board-of-
--   directors, executive-committee (subset of the board, flagged
--   inline), directors-emeritus, and advisory-board pages; photos
--   vendored under public/leadership/ (no hotlinking). Purpose
--   section text extracted from the Purpose-Vision-Mission one-pager
--   image; the Marquardt quote graphic (Quote2.jpg) is rendered as a
--   native quote block; session photos (IMG_3408 banner thumb,
--   IMG_5388) vendored under public/about/.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0002',
    null,
    'about',
    'About WIAL',
    true,
    jsonb_build_object(
        'heroIntro', 'The World Institute for Action Learning (WIAL) is the world’s leading certifying body for Action Learning, providing various training & certification programs internationally. It is a rapidly growing international not-for-profit organization supported by WIAL Affiliates around the world. WIAL is a highly capable global organization helping clients rapidly solve urgent and important business challenges. Our clients frequently achieve a substantial Return on Investment (ROI) on their organization, leadership, and team development projects.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Founded', 'value', '1995'),
            jsonb_build_object('label', 'Global Affiliates', 'value', '15+'),
            jsonb_build_object('label', 'Certification Levels', 'value', '4')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'prose',
                'title', 'Purpose',
                'paragraphs', jsonb_build_array(
                    'In our rapidly changing world, organizations struggle to meet their ambitious performance and people development goals with the methods they have used in the past.',
                    'We transform ambitious organizations into places of continuous learning, making them capable of solving today''s challenges and embracing the opportunities of tomorrow through the promotion and practice of action learning.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Mission',
                'paragraphs', jsonb_build_array(
                    'WIAL coaches elevate team performance through action learning. They support teams in identifying breakthrough solutions to real problems, while accelerating individual, team and organization development. WIAL''s team coaching leads to more effective organizations, positive business impact and a learning culture.'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Vision',
                'paragraphs', jsonb_build_array(
                    'We believe that ambitious organizations need new ways of thinking, doing business, and collaborating to solve their complex problems and achieve their desired results. WIAL envisions a world where Action Learning is the standard approach for developing leaders and solving critical organizational challenges.'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'What We Do',
                'image', '/about/action-learning-team.jpg',
                'imageAlt', 'A team working through real business problems around the table at a WIAL Action Learning session',
                'imagePosition', 'left',
                'paragraphs', jsonb_build_array(
                    'WIAL coaches elevate team performance through Action Learning. They support teams in identifying breakthrough solutions to real problems, while accelerating individual, team and organizational development. WIAL''s team coaching leads to more effective organizations, positive business impact and a learning culture.',
                    'The World Institute for Action Learning provides training and certification programs internationally and is supported by affiliates around the world. Our certification programs include CALC (Certified Action Learning Coach), PALC (Professional Action Learning Coach), SALC (Senior Action Learning Coach), and MALC (Master Action Learning Coach).'
                )
            ),
            jsonb_build_object(
                'type', 'media_prose',
                'title', 'The History of Action Learning',
                'image', '/about/action-learning-session.jpg',
                'imageAlt', 'A WIAL Action Learning coach leading a team session',
                'paragraphs', jsonb_build_array(
                    'Professor Reginald Revans is the originator of Action Learning. He invented and developed this method in the United Kingdom in the 1940s, working in the Coal Board. He encouraged managers to meet together in small groups, to share their experiences and ask each other questions about what they saw and heard. The approach increased productivity by over 30%.',
                    'In 1995, WIAL co-founder Michael Marquardt met Reg Revans, widely recognized as the father of Action Learning. The two men began a dialogue that led to the development of the WIAL model of Action Learning, which focuses on continual learning. After years of testing, research and refinement, the model took final form in the renowned six components and two ground rules of Action Learning.',
                    'Today, WIAL continues to advance the practice of Action Learning through rigorous certification, research, and a global community of practitioners.'
                ),
                'caption', 'Action Learning''s foundation was built on collaborative problem solving.',
                'imagePosition', 'right'
            ),
            jsonb_build_object(
                'type', 'quote',
                'quote', 'Action Learning is a problem-solving and leadership development process that involves a small group working on a real problem, taking action, and learning as individuals, as a team, and as an organization while doing so.',
                'attribution', 'Dr. Michael Marquardt, WIAL co-founder'
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Impact',
                'paragraphs', jsonb_build_array(
                    'WIAL certification is recognized internationally as the gold standard for Action Learning coaching. Our certified coaches work with organizations across sectors including technology, healthcare, finance, education, and government.',
                    'WIAL is an ICF-accredited training provider, and our CALC certification is an accredited ICF CCE program, ensuring that our coaches meet the highest professional standards.'
                )
            ),
            jsonb_build_object(
                'type', 'people_grid',
                'title', 'Board of Directors',
                'description', 'WIAL is governed by a volunteer Board of Directors drawn from the global Action Learning community. The President, Vice President, and Treasurer together form the Executive Committee, and the board is supported by WIAL''s Executive Director.',
                'items', jsonb_build_array(
                    jsonb_build_object('name', 'Isa Jamaluddin', 'role', 'President', 'eyebrow', 'Executive Committee', 'image', '/leadership/isa-jamaluddin.jpg'),
                    jsonb_build_object('name', 'Lynda White', 'role', 'Vice President', 'eyebrow', 'Executive Committee', 'image', '/leadership/lynda-white.jpg'),
                    jsonb_build_object('name', 'Jonathan Kenger', 'role', 'Treasurer', 'eyebrow', 'Executive Committee', 'image', '/leadership/jonathan-kenger.jpg'),
                    jsonb_build_object('name', 'Els Van de Water', 'role', 'Director, Better World Fund', 'image', '/leadership/els-van-de-water.jpg'),
                    jsonb_build_object('name', 'Ana Maria Maia Gonçalves', 'role', 'Director, Certification', 'image', '/leadership/ana-maria-maia-goncalves.jpg'),
                    jsonb_build_object('name', 'Marie Tseng', 'role', 'Director, Affiliates', 'image', '/leadership/marie-tseng.jpg'),
                    jsonb_build_object('name', 'Tomasz Janiak', 'role', 'Director, Marketing', 'image', '/leadership/tomasz-janiak.jpg'),
                    jsonb_build_object('name', 'Phuong Dao', 'role', 'Director, Education & Research', 'image', '/leadership/phuong-dao.jpg'),
                    jsonb_build_object('name', 'Sumaia Thomas', 'role', 'Director, Coaches', 'image', '/leadership/sumaia-thomas.jpg'),
                    jsonb_build_object('name', 'Mark Relova, Ph.D.', 'role', 'Executive Director', 'eyebrow', 'Supported by', 'image', '/leadership/mark-relova.jpg')
                )
            ),
            jsonb_build_object(
                'type', 'people_grid',
                'title', 'Directors Emeritus',
                'description', 'WIAL honors the past board members whose leadership and long service shaped the institute, including co-founder Dr. Michael Marquardt.',
                'items', jsonb_build_array(
                    jsonb_build_object('name', 'Dr. Skip Leonard', 'role', 'Director Emeritus', 'image', '/leadership/skip-leonard.jpg'),
                    jsonb_build_object('name', 'Dr. Michael Marquardt', 'role', 'Director Emeritus', 'image', '/leadership/michael-marquardt.jpg'),
                    jsonb_build_object('name', 'Dr. Bea Carson', 'role', 'Director Emeritus', 'image', '/leadership/bea-carson.jpg'),
                    jsonb_build_object('name', 'Dr. Chuck Appleby', 'role', 'Director Emeritus', 'image', '/leadership/chuck-appleby.jpg'),
                    jsonb_build_object('name', 'Dr. Peter Loan', 'role', 'Director Emeritus', 'image', '/leadership/peter-loan.jpg'),
                    jsonb_build_object('name', 'Dr. Ng Choon Seng', 'role', 'Director Emeritus', 'image', '/leadership/ng-choon-seng.jpg'),
                    jsonb_build_object('name', 'Dr. Arthur M. Freedman', 'role', 'Director Emeritus', 'image', '/leadership/arthur-freedman.jpg'),
                    jsonb_build_object('name', 'Peter Cauwelier, PhD', 'role', 'Director Emeritus', 'image', '/leadership/peter-cauwelier.jpg')
                )
            ),
            jsonb_build_object(
                'type', 'people_grid',
                'title', 'Advisory Board',
                'description', 'Members of the WIAL Advisory Board include internationally recognized thought leaders and proponents of Action Learning.',
                'items', jsonb_build_array(
                    jsonb_build_object('name', 'Nick Hixson', 'role', 'United Kingdom', 'eyebrow', 'Chair', 'image', '/leadership/nick-hixson.jpg'),
                    jsonb_build_object('name', 'Agata Dulnik', 'role', 'Poland', 'image', '/leadership/agata-dulnik.jpg'),
                    jsonb_build_object('name', 'Bob Hoffman', 'role', 'USA', 'image', '/leadership/bob-hoffman.jpg'),
                    jsonb_build_object('name', 'Jane McConnell', 'role', 'France & USA', 'image', '/leadership/jane-mcconnell.jpg'),
                    jsonb_build_object('name', 'Kimo Kippen', 'role', 'USA', 'image', '/leadership/kimo-kippen.jpg'),
                    jsonb_build_object('name', 'Luciana Rabay', 'role', 'Brazil', 'image', '/leadership/luciana-rabay.jpg'),
                    jsonb_build_object('name', 'M. Ian Blanchard', 'role', 'Caribbean', 'image', '/leadership/ian-blanchard.jpg'),
                    jsonb_build_object('name', 'Magdalene Mook', 'role', 'Poland & USA', 'image', '/leadership/magdalene-mook.jpg'),
                    jsonb_build_object('name', 'Mary Kay Vona', 'role', 'USA', 'image', '/leadership/mary-kay-vona.jpg'),
                    jsonb_build_object('name', 'Rita Meyerson', 'role', 'USA', 'image', '/leadership/rita-meyerson.jpg'),
                    jsonb_build_object('name', 'Shannon Banks', 'role', 'United Kingdom', 'image', '/leadership/shannon-banks.jpg'),
                    jsonb_build_object('name', 'V. Ganesh Varatharajoo', 'role', 'Malaysia', 'image', '/leadership/ganesh-varatharajoo.jpg')
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Better World Fund',
                'body', 'Supporting Action Learning for social impact',
                'href', '/better-world',
                'label', 'Learn More'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Conferences',
                'body', 'Join our global Action Learning events',
                'href', '/conferences',
                'label', 'View Events'
            ),
            jsonb_build_object('type', 'cta', 'title', 'Awards', 'body', 'Recognizing excellence in Action Learning', 'href', '/awards', 'label', 'See Awards')
        )
    ),
    jsonb_build_object(
        'description', 'Learn about the World Institute for Action Learning (WIAL) - the world''s leading certifying body for Action Learning, our mission, vision, history, and global impact.',
        'sourceUrl', 'https://wial.org/about-us/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Full content migrated from wial.org/about-us/ with Better World Fund, Conferences, and Awards links added (Awards now internal at /awards). Leadership consolidated from wial.org board-of-directors, executive-committee (subset of the board, flagged inline), directors-emeritus, and advisory-board pages; photos vendored under public/leadership/ (no hotlinking). Purpose section text extracted from the Purpose-Vision-Mission one-pager image; the Marquardt quote graphic (Quote2.jpg) is rendered as a native quote block; session photos (IMG_3408 banner thumb, IMG_5388) vendored under public/about/.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
