-- ============================================================
-- Migration: Upsert the "Our Partners" page (slug: partners)
-- Source: https://wial.org/become-a-partner/
-- Generated by scripts/generate-page-migration.py from the
-- src/content/pages.json entry — edit the fixture and regenerate
-- instead of editing this file by hand.
--   Rewritten from the live Become a Partner page (issue #117).
--   Added the missing 8th-reason card (global collaboration) and two
--   pricing sections (not-for-profit and for-profit tiers, matching
--   the "Partner tiers: 2" / "Pricing bands: 7" metrics, which the
--   previous draft did not actually show). Dropped four decorative
--   stock photos (a client-header banner, a reasons-recap
--   infographic whose text duplicates the feature grid, a Zoom-call
--   photo, and a handshake CTA photo) — none showed partner-specific
--   content. The legacy inline inquiry form and its dead link to an
--   archived, richer "WIAL Partner Application" (business/contact
--   name, address, org description, Action Learning experience, WIAL
--   connections) were merged into one form at /partners/apply,
--   dropping the WPForms honeypot and mailing-address fields.
--   "Browse partners" intentionally still points to the live
--   directory.wial.org/partners — a separate site we do not migrate.
-- ============================================================

insert into public.content_pages (
    id,
    chapter_id,
    slug,
    title,
    published,
    body_richtext,
    seo,
    created_at,
    updated_at
)
values (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0008',
    null,
    'partners',
    'Our Partners',
    true,
    jsonb_build_object(
        'heroIntro', 'Partners work directly with WIAL Global — organizations, for-profit or non-profit, that support the use of the WIAL methodology to solve problems, develop leaders, build teams, and transform organizations. Partners are distinct from affiliates.',
        'metrics', jsonb_build_array(
            jsonb_build_object('label', 'Partner tiers', 'value', '2'),
            jsonb_build_object('label', 'Pricing bands', 'value', '7'),
            jsonb_build_object('label', 'Global reach', 'value', 'Worldwide')
        ),
        'sections', jsonb_build_array(
            jsonb_build_object(
                'type', 'feature_grid',
                'title', 'Why organizations partner with WIAL',
                'items', jsonb_build_array(
                    jsonb_build_object(
                        'eyebrow', 'Standing',
                        'title', 'Global recognition',
                        'body', 'Connect with the prestige and reach of WIAL, the global leader in Action Learning.'
                    ),
                    jsonb_build_object('eyebrow', 'Revenue', 'title', 'New revenue streams', 'body', 'Generate additional resources and revenue for your organization.'),
                    jsonb_build_object(
                        'eyebrow', 'Network',
                        'title', 'Global professional network',
                        'body', 'Expand your professional networks and outreach to every corner of the globe.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Support',
                        'title', 'Priority support',
                        'body', 'Get priority assistance applying the WIAL Action Learning methodology to your programs.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Research',
                        'title', 'Research and best practices',
                        'body', 'Access WIAL publications, newsletters, and cutting-edge Action Learning research.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Collaboration',
                        'title', 'Global collaboration',
                        'body', 'Collaborate with WIAL leaders, coaches, partners, and clients around the world.'
                    ),
                    jsonb_build_object(
                        'eyebrow', 'Pricing',
                        'title', 'Reduced program fees',
                        'body', 'Get reduced fees for WIAL programs and conferences, plus co-branding opportunities.'
                    )
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Not-for-profit pricing',
                'paragraphs', jsonb_build_array(
                    'Annual partner fees for not-for-profit organizations are set by employee count:'
                ),
                'bullets', jsonb_build_array(
                    'Fewer than 50 employees — $250 a year',
                    '50–500 employees — $500 a year',
                    'More than 500 employees — $1,000 a year'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'For-profit pricing',
                'paragraphs', jsonb_build_array(
                    'Annual partner fees for for-profit organizations are set by employee count:'
                ),
                'bullets', jsonb_build_array(
                    '1–9 employees — $500 a year',
                    '10–99 employees — $1,000 a year',
                    '100–499 employees — $2,000 a year',
                    'More than 500 employees — $3,000 a year'
                )
            ),
            jsonb_build_object(
                'type', 'prose',
                'title', 'Partner directory',
                'paragraphs', jsonb_build_array(
                    'Browse the full WIAL partner directory to see current organizations partnering with WIAL worldwide.'
                )
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Browse partners',
                'body', 'Explore the full directory of WIAL partners and their services.',
                'href', 'http://directory.wial.org/partners',
                'label', 'View directory'
            ),
            jsonb_build_object(
                'type', 'cta',
                'title', 'Become a partner',
                'body', 'Join WIAL''s global network of partners and help advance Action Learning.',
                'href', '/partners/apply',
                'label', 'Apply now'
            )
        )
    ),
    jsonb_build_object(
        'description', 'WIAL''s global network of partners advancing Action Learning worldwide.',
        'sourceUrl', 'https://wial.org/become-a-partner/',
        'sourceStatus', 'migrated-from-wial',
        'sourceNotes', 'Rewritten from the live Become a Partner page (issue #117). Added the missing 8th-reason card (global collaboration) and two pricing sections (not-for-profit and for-profit tiers, matching the "Partner tiers: 2" / "Pricing bands: 7" metrics, which the previous draft did not actually show). Dropped four decorative stock photos (a client-header banner, a reasons-recap infographic whose text duplicates the feature grid, a Zoom-call photo, and a handshake CTA photo) — none showed partner-specific content. The legacy inline inquiry form and its dead link to an archived, richer "WIAL Partner Application" (business/contact name, address, org description, Action Learning experience, WIAL connections) were merged into one form at /partners/apply, dropping the WPForms honeypot and mailing-address fields. "Browse partners" intentionally still points to the live directory.wial.org/partners — a separate site we do not migrate.'
    ),
    now(),
    now()
)
on conflict (slug) where chapter_id is null
do update set
    title = excluded.title,
    published = excluded.published,
    body_richtext = excluded.body_richtext,
    seo = excluded.seo,
    updated_at = now();
